### ISSUE TITLE
Response validation occurs before data entry

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#1001]
**Describe the bug**
Questionnaire Response validation happens on form init before any data entry. This marks the whole form in red validation errors.

Validation happen on com/google/android/fhir/datacapture/QuestionnaireViewModel.kt init around line 56->validateQuestionnaireResponseItems

**Component**
SDC library

**To Reproduce**
1. Open any form that has validations
2. See fields highlighted in red
3. <img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/148216106-9664d9d6-2f93-4652-8107-6c1cad71f3e8.png"/>

**Expected behavior**
Form should show error only if field has wrong data OR on form submit (handled by consumer app)

**Comment by jingtang10** [comment]
Thanks for creating this issue @maimoonak.

While there probably exists an easier fix, I think we should also figure out if we want to create a validation configuration that developers can provide to change the validation behavior.

**Comment by f-odhiambo** [comment]
@Tarun-Bhardwaj can you assign https://github.com/aurangzaibumer to this ticket 

CC @aurangzaibumer

**Comment by aurangzaibumer** [comment]
do we need configuration on each form or it should be same for all forms in app (app level setting). Need suggestions
@jingtang10 @aditya-07

**Comment by f-odhiambo** [comment]
@jingtang10 Based  on your comment below, should we make the changes in this or a new ticket ?
`we should also create a library configuration that allows different types of validation. e.g. per-page, or validate on submission, or no validation at all.`

**Comment by jingtang10** [comment]
so if you open a questionnaire with some existing answers, and those existing answers are failing validation, do you want to display those errors?

for example, you have a patient questionnaire, and you're loading it with existing patient data, some of the answers are failing validation. are you ok with these errors not shown at first?

**Comment by dubdabasoduba** [comment]
> so if you open a questionnaire with some existing answers, and those existing answers are failing validation, do you want to display those errors?
> 
> for example, if you have a patient questionnaire, and you're loading it with existing patient data, some of the answers are failing validation. are you ok with these errors not being shown at first?

I think I would be okay with showing those errors. The error here would be based on data on the input field as opposed to the one that occurs without any data on the input field.

**Comment by rowo** [comment]
I agree with Benjamin (the errors should appear). With the errors appearing on load, it is kind of like a required field indicator and tells the user they should interact with the fields rather than surprising them at form submit. This isn't really relevant, but curious in the situation described, would the only options would be the remove the errors and submit, or cancel and not be able to save anything?

**Comment by aurangzaibumer** [comment]
for example

NEW FORM
errors should not be shown on start

EDIT FORM
for suppose if first name was required but somehow it wasn't saved when it was registered
now we are trying to open it on edit form where FIRST NAME is mandatory now to enter
in this case, as soon as form loads/opens it should throw error on FIRST NAME field right? rather than showing error on submit button

probably this is the requirement, please correct me if If there is any gap in understanding @jingtang10 
cc @dubdabasoduba

**Comment by aurangzaibumer** [comment]
> so if you open a questionnaire with some existing answers, and those existing answers are failing validation, do you want to display those errors?
> 
> for example, you have a patient questionnaire, and you're loading it with existing patient data, some of the answers are failing validation. are you ok with these errors not shown at first?

for example

NEW FORM
errors should not be shown on start

EDIT FORM
for suppose if first name was required but somehow it wasn't saved when it was registered
now we are trying to open it on edit form where FIRST NAME is mandatory now to enter
in this case, as soon as form loads/opens it should throw error on FIRST NAME field right? rather than showing error when submit button presses.

probably this is the requirement, please correct me if If there is any gap in understanding @jingtang10
cc @dubdabasoduba

**Comment by Tarun-Bhardwaj** [comment]
@aurangzaibumer , what's the ETA you're targeting to close this issue?

**Comment by aurangzaibumer** [comment]
> @aurangzaibumer , what's the ETA you're targeting to close this issue?

Hello Tarun, this is already merged on monday with the following PR https://github.com/google/android-fhir/pull/1309

**Comment by jingtang10** [comment]
thanks @aurangzaibumer for the update. yes umer is right this issue should be closed.
