### ISSUE TITLE
Update mechanism from PATCH to PUT or have a hybrid approach for P2P Sync on FHIR Engine and Sync API

### ISSUE THREAD

**Issue by f-odhiambo** [google/android-fhir#1091]
**Is your feature request related to a problem? Please describe.**
Peer-to-Peer  Sync support on SDK 

- The biggest challenge around implementing P2P sync comes from the way that server sync has been implemented in the Android FHIR engine. Changes to resources are synced to the server using the patch interaction rather than the update interaction which means that when a peer is syncing to the server after having synced from another peer, it needs the list of changes which were made to the resource rather than the latest version of the resource itself. 

**Describe the solution you'd like**

- The planned approach is to sync the locally updated version of the resource along with the local changes to the resource from the sender to the receiver, and then store them as-is on the receiver side.
- When doing normal sync we use the PATCH but when doing P2P sync you should switch to PUT mechanism  for resources update . The PUT method uses the request URI to supply a modified version of the requested resource which replaces the original version of the resource, whereas the PATCH method supplies a set of instructions to modify the resource.
- This can be a hybrid approach for which can be switched on demand depending on which sync approach is desired either 'Normal Sync' or 'P2P Sync' 

**Additional context**
1. Review P2P Support on SDK Document shared
2. Review - Sync Pitfall - https://github.com/google/android-fhir/discussions/806
3. Review the following classes  
        - Sync Class  https://github.com/google/android-fhir/blob/d3c3feda998e7c7fdc20c07b539247c892c0fb72/engine/src/main/java/com/google/android/fhir/sync/Sync.kt 
        - Synchronizer class https://github.com/google/android-fhir/blob/d3c3feda998e7c7fdc20c07b539247c892c0fb[…]/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt

**Comment by aditya-07** [comment]
@f-odhiambo P2P sync shouldn't be driven by current Sync module (i.e `Synchronizer` & internally `FhirEngine.syncUpload / FhirEngine.syncDownload`) since it is designed to be talking to a server. 
Instead, a separate P2P sync module on the sender app should just ask the FhirEngine to give it  a list of LocalChanges (_we will have to design a new api for this_) and Sync it to the receiver app. The receiver app on the other hand should use the available FhirEngine api's to process/save it.

**Comment by f-odhiambo** [comment]
This is noted @aditya-07, I will  schedule a check in call to further discuss this

**Comment by ekigamba** [comment]
I've tried going through the docs and issue I think patch is still superior in our case since we only edit the changed properties and not the whole resource. I might need some more understanding in case this is not correct. However, I gathered the following:

1. We need to tie the patches to the resource version that was modified on the client so that this can be pushed to the server
2. The server needs to have the ability to conditionally apply patches based on the version
3. We need to have a solution for applying outdated-patches. If we assume that the same resource can be modified simultaneously on different devices, then if one of the devices sends an update to the server, the resource version changes and device 2 has an outdated patch that will possibly be rejected by the server. The situation becomes more complicated if the device is offline for long such that the patch is behind by several versions and cannot be automatically. 

However, I believe we can make some assumptions that the latest patch should provide all the updates since all the unsynced updates would be added to the resource by the user at that point given that the user can easily confirm/evaluate that the data is not up-to-date or incorrect eg. If a patients address was previously updated but the changes have not been received on another device/point-of-care, the patient will provide all the updated details again and this will be recorded by the health worker


https://hl7.org/fhir/http.html#concurrency

**Comment by ekigamba** [comment]
### Notes from the discussion on 12/02/2022

How to solve applying/syncing outdated-patches?

- This needs time to be clearly thought-out. These become merge-conflicts. We can possibly have the users provide guidance on how to merge the patches and alternatively provide an automated way to handle this

**Comment by f-odhiambo** [comment]
I think we can do the implementation for the desired P2P sync support on SDK via issue https://github.com/google/android-fhir/issues/1178.  I think we can close this and reopen later if needed 

CC @Tarun-Bhardwaj @jingtang10 @aditya-07

**Comment by Tarun-Bhardwaj** [comment]
> I think we can do the implementation for the desired P2P sync support on SDK via issue #1178. I think we can close this and reopen later if needed
> 
> CC @Tarun-Bhardwaj @jingtang10 @aditya-07

Closing the issue based on comments from Francis.
