### ISSUE TITLE
Engine - Fetch resources using Query

### ISSUE THREAD

**Issue by prajapati-chirag** [google/android-fhir#1103]
**Is your feature request related to a problem? Please describe.**
We need to fetch resources using dynamic conditions, users can buildup resource conditions into the portal, and as per condition fetch resources into the mobile side.

**Describe the solution you'd like**
For the above problem, We need to fetch resources using the query. So to create a query as per dynamic conditions and fetch the required resources.

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by jingtang10** [comment]
Hi @prajapati-chirag, thanks for raising this issue.

The way FHIR engine allows for search to happen is via the search API. Please see this PR for some code example: #395.

In short you should be able to use our Kotlin API to search instead of using raw queries. The way you build up your request in the Kotlin API is the same as how you'd build up SQL queries. For another example, please see here https://github.com/google/android-fhir/blob/6c2046d9344e0bfafefa9e14736c62be3cd25961/demo/src/main/java/com/google/android/fhir/demo/PatientListViewModel.kt#L91 for how to search for patients in a particular city. More complex search quries can be built the same way.

Can you share more on your use case so we can see if there's any gap in the kotlin search API we have?

Admittedly the documentation here https://github.com/google/android-fhir/wiki/FHIR-Engine-Library#search-fhir-resources needs updating. We're working on it!

**Comment by prajapati-chirag** [comment]
Hi @jingtang10, Thanks for your feedback.

Multiple criteria of search filters in android need to be implemented dynamically from a Web UI using a portal. Presently to provide it dynamically using search API would result in a complex search API code. Additionally, modifier ENUMs (StringFilterModifier.CONTAINS, StringFilterModifier.MATCHES_EXACTLY) are dependent on the search field, but the search field is also dynamic. 

For example: 
fhirEngine.search<Patient> {
  filter(Patient.ADDRESS_CITY) {
    prefix = ParamPrefixEnum.EQUAL
    value = "NAIROBI"
  }
  sort(Patient.GIVEN, Order.ASCENDING)
  count = 10
  from = 10
}

How to perform filter when Patient.ADDRESS_CITY filed and modifier ParamPrefixEnum. EQUAL is dynamic. 
For example, In one scenario filter patients using names that exactly match or contain criteria, and another scenario filter patients using Birthdate less than the particular date or equal to the particular date.

Please suggest how to filter dynamic way.

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 , is this something we are still looking at?

**Comment by kunjan8794** [comment]
Thanks, @jingtang10 - I think this is a really good alternative to the query approach. We'll definitely try this out.

**Comment by Tarun-Bhardwaj** [comment]
@kunjan8794 , could you please confirm if the solution provided by Jing is working for you? We'll close this issue accordingly.
CC: @jingtang10

**Comment by jingtang10** [comment]
@kunjan8794 can you check this please?

**Comment by prajapati-chirag** [comment]
@jingtang10 @Tarun-Bhardwaj Above solution works for us.
