### ISSUE TITLE
Catalog, error states workflow.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1170]
**Is your feature request related to a problem? Please describe.**

1. Design questionnaire json for error states.
2. Launch error state questionnaire screen on click of error states component on landing page.
3. Navigate back to landing page when click on back key on error state screen.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
<img width="433" alt="Screen Shot 2022-02-15 at 5 26 11 PM" src="https://user-images.githubusercontent.com/86107848/154057838-63b9ac2a-770b-4034-8b72-0c0cf3927a55.png">

**Comment by santosh-pingle** [comment]
@shelaghm

**Comment by shelaghm** [comment]
Thanks @santosh-pingle , looking at this I realize that the error message line for multiple/single choice actually is displayed above the item since there's usually multiple radio buttons/checkboxes in a list. I made some changes to the design to make this more clear. I also added a new error state for invalid date format (do we have this functionality?) to demonstrate how it will look in a completed state. Thoughts?
![Error states](https://user-images.githubusercontent.com/86378921/154600322-20f39559-501f-496c-bb6a-b04d7b8fac6f.png)

**Comment by santosh-pingle** [comment]
looking into it!

**Comment by santosh-pingle** [comment]
<img width="415" alt="Screen Shot 2022-02-18 at 5 35 47 PM" src="https://user-images.githubusercontent.com/86107848/154680730-9ffb70f0-559e-48d9-9ae2-d163c62257cd.png">

**Comment by santosh-pingle** [comment]
Action items : 
1.  Show gear icon in app bar
2. Show bottom sheet on gear icon click.
3. Show Hide/Show error button on bottom sheet.

**Comment by santosh-pingle** [comment]
Action items : 

- Design questionnaire json with required field true.
- On error state button click show error questionnaire json
- On hide error button click show questionnaire json without error.
- Repeat above action items for all components.
