### ISSUE TITLE
SDC Catalog app: Date picker - Keyboard doesn't open when clicking text field

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1418]
**Describe the bug**
When clicking the text field on the DatePicker or DateTime picker, the keyboard doesn't open. 

**Component**
SDC gallery app

**To Reproduce**
1. Go to SDC catalog app
2. Click on Date picker
3. Click on text field (not the calendar icon)

**Expected behavior**
The expected behavior is that manual keyboard based entry should be possible. We show a date format and only allow numerical date entry.

**Screenshots**
![Screenshot_20220524-145927-1](https://user-images.githubusercontent.com/86378921/170192486-1c76196c-3210-443d-8e7b-bf77b3a1569d.jpg)

**Comment by shelaghm** [comment]
@jingtang10 @aditya-07 tagging you for visibility for dependencies. Please also help prioritize.

**Comment by jingtang10** [comment]
@aditya-07 disabled this in a previous PR. the reason was that we do not have a good way of ensuring the user enters well-formed date time string and validating it. at the moment, the dialog opens if the user clicks the icon. we do need to eventually re-enable this. but we do need to look into a solution that actually works.

@aditya-07 to comment.

**Comment by shelaghm** [comment]
Team discussion: 
- Open keyboard (no dialog opens) when pressing input box (not the calendar icon)
- Validate using android system date format.

**Comment by santosh-pingle** [comment]
in progress.
