### ISSUE TITLE
Completion Bar on top of each page in SDC to make users aware of the unanswered questions covered by the keyboard

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#1539]
**Is your feature request related to a problem? Please describe.**
As can be seen in the video, the keyboard covers up questions in a particular page. It is difficult for non-technical people to realize that there is a scroll bar that must be used to answer the rest of the questions.

**Describe the solution you'd like**
I was thinking that we could have a bar at the top that progresses as the questions in a page are answered. So that the instruction to first time users can be simple eg: "Answer all questions on the page until the bar is complete"

**Describe alternatives you've considered**
We could also have a text box that says 2 out 3 answered or 2/3 . @shelaghm Please suggest any other ideas.

https://user-images.githubusercontent.com/48797364/183082175-23eee450-768d-473c-9d7f-e4aeed7a1726.mp4

**Additional context**

cc: @jingtang10

**Comment by shelaghm** [comment]
@joiskash @jingtang10 I'm not sure what's the best approach here. For context, we are planning to implement a progress bar for paginated questionnaires https://github.com/google/android-fhir/issues/1523 which would behave a bit differently from the proposed solution on this issue. It might be confusing to have a progress bar that only indicates progress on one page of the questionnaire, not the whole questionnaire. 

An alternative is to consider putting the back and next buttons anchored at the bottom of the questionnaire, so that users need to scroll to the bottom of the page to press next. 

Another alternative is to consider adding a dialog box that appears when they press next that says something like "there's two unanswered questions/fields on this page"

**Comment by jingtang10** [comment]
actually this is not a duplicate of 1523.

@joiskash we're saying that for paginated questionnaire we have 1 progress bar on top indicating where you are amonst the pages. it would be hard and confusing to include another progress bar to indicate the scrolling status of the current page. as shelagh suggested, the best way to approach this is to make sure when you have paginated questionnaire, each page fits in the screen.

**Comment by joiskash** [comment]
Ok but this is not an optimum solution. Considering different phone screen size , table vs mobile. Etc. This would mean created different questionnaires for different screen size. Or else the feedback that we will receive (and have received)  is that more questions can be added to a page instead of leaving it half empty.
