### ISSUE TITLE
Validation: Highlight the required fields when a user submits a form

### ISSUE THREAD

**Issue by Itskiprotich** [google/android-fhir#1576]
**Is your feature request related to a problem? Please describe.**
With the SDC beta04, when I try to submit a form with unanswered required fields, it's hard to tell which field is required since the highlight only appears when a user interacts with a specific input field. Is it possible to allow the validators be seen at a glance?

**Describe the solution you'd like**
Is it possible to have all the required fields marked as shown below in the screenshot? 

**Describe alternatives you've considered**
None
![Screenshot_20220831_094028](https://user-images.githubusercontent.com/26279422/187613624-11118401-cee8-4bc5-b0c0-c695e999e67b.png)

**Additional context**

**Comment by f-odhiambo** [comment]
This is related https://github.com/google/android-fhir/issues/544

**Comment by jingtang10** [comment]
can you please share the questionnaire? @Itskiprotich 

thanks

**Comment by jingtang10** [comment]
@Itskiprotich The reason that we do not show all these validation errors is because we do not want to spam the user when they first open the questionnaire. We discussed this with @mberg @f-odhiambo @shelaghm. Showing all these validation errors at the same time when the user first open the questionnaire is considered as an unhelpful pattern.

Unless there's a differernt solution, I will just mark this as a duplicate issue as #544 as @f-odhiambo suggested.

**Comment by jingtang10** [comment]
@Itskiprotich can you confirm if you can use the submit button provided by the library (which uses the fragment results API)? rather than calling the `getQuestionnaireResponse` API?

Discussed with @aditya-07 and @shelaghm. It remains a question what the questionnaire behavior should be when there are either validation errors on the last page, or previous pages (in the case of random entry mode, you can navigate to the next page without having completed everything in the current page, so it's possible that when you're on the last page, there're still unanswered questions in previous pages). Should we have a pop-up dialog? an inline widget? a toast? or some kind of more flexible API for developers to provide feedback to the user however they like.

**Comment by shelaghm** [comment]
I think a pop-up dialog that is displayed when a user presses "submit" can work well here because we want to alert people take action and fix the issues. There should also be error messages already displayed in the form if they haven't completed required questions or there's validation errors. 

Screenshot w/ example
<img width="443" alt="Screen Shot 2022-09-28 at 16 25 27" src="https://user-images.githubusercontent.com/86378921/192905788-e2c92fbf-e7e6-41c3-815f-8df2862aadc0.png">

What do you think of this approach @aditya-07 and @jingtang10?

**Comment by Itskiprotich** [comment]
Sorry for the delay.

Attached is the questionnaire I'm using.
[baby-monitoring.zip](https://github.com/google/android-fhir/files/9771570/baby-monitoring.zip)

**Comment by jingtang10** [comment]
i think in the V1 we should have "complete fields" and "submit anyway" buttons in the dialog just because in some cases the healthworker might want to save a draft questionnaire

**Comment by jingtang10** [comment]
@shelaghm i think the text in the dialog needs to be more generic. "complete all required fields" doesn't cover the cases where validation is failing for other reasons, e.g., value too large/small, text too long/short etc.

**Comment by shelaghm** [comment]
@jingtang10 How about some of these options? Is `incomplete questionnaire` generic enough? I was thinking it could cover both the scenario of missing questions or that there are errors causing the questionnaire to be incomplete. Another option is to describe all of it as "errors" without making a distinction of what kind of error it is. Thoughts?

<img width="1424" alt="Screen Shot 2022-11-29 at 15 50 28" src="https://user-images.githubusercontent.com/86378921/204673683-9a552726-6f2d-4b83-8a71-f876358b5ada.png">

**Comment by jingtang10** [comment]
@shelaghm nit: let's use anyway instead of anyways since anyways is the informal version of anyway.

**Comment by shelaghm** [comment]
@jingtang10 sounds good, I'll make the change in my mocks
@aditya-07 please use "save anyway" when working on this issue
