### ISSUE TITLE
Move error message for boolean/single/multiple choice type widgets to above the choices

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1586]
**Describe the bug**
When error message get shown below the sdc components like boolean choice, single choice etc, there is not enough margin in between view and error text. 

**Component**
SDC library

**Expected behavior**
It is expected to show enough margin in between view and error texts.

**Screenshots**
<img width="430" alt="Screen Shot 2022-09-08 at 11 46 56 AM" src="https://user-images.githubusercontent.com/86107848/189049052-024e7592-37fb-4caf-8204-03b0e2e08958.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by shelaghm** [comment]
What is the padding right now? @santosh-pingle 
- Adjust it to 4px padding between text box and hint text/error text

**Comment by vj-codes** [comment]
@shelaghm @Tarun-Bhardwaj hey can I work on this?

**Comment by jingtang10** [comment]
@vj-codes sorry santosh had already started - please pick another unassigned issue tagged as ux (for example #1588)

@shelaghm i feel 4dp is not enough - please see santosh's screenshots in #1655.

**Comment by jingtang10** [comment]
took another look with @santosh-pingle. it feels like for things like single choice, because there are multiple radio buttons, the error message should be a little bit further from them to make it look like it's for the entire question and not just the last item.

but i do understand that the error message is fairly close in the cases of text input (where that's just the default material behavior as we use the material component to show the text and error). so maybe there's also a consideration for consistency.

**Comment by shelaghm** [comment]
@jingtang10 @santosh-pingle I read https://github.com/google/android-fhir/pull/1655 and this issue in the wrong order. I'll go back an edit my other response. 

Placement: I think the error message should be at the top of the list, in the field we call `instructions`. I elaborated on this in https://github.com/google/android-fhir/pull/1655
Spacing: @santosh-pingle what is the line spacing on the text element for the `EntryFormat / error` text? 
According to our M3 guidelines, the line height of the text is 16px, the font is 12px and with 4px padding. I'm guessing the issue is that the text line spacing is not 16px, which is why it looks like less padding than it should be?

Attached screenshot to hopefully explain. 
<img width="675" alt="Screen Shot 2022-10-07 at 11 47 26" src="https://user-images.githubusercontent.com/86378921/194628929-d7227696-8711-4718-b624-8c545250715e.png">

**Comment by santosh-pingle** [comment]
> @jingtang10 @santosh-pingle I read #1655 and this issue in the wrong order. I'll go back an edit my other response.
> 
> Placement: I think the error message should be at the top of the list, in the field we call `instructions`. I elaborated on this in #1655 Spacing: @santosh-pingle what is the line spacing on the text element for the `EntryFormat / error` text? According to our M3 guidelines, the line height of the text is 16px, the font is 12px and with 4px padding. I'm guessing the issue is that the text line spacing is not 16px, which is why it looks like less padding than it should be?
> 
> Attached screenshot to hopefully explain. <img alt="Screen Shot 2022-10-07 at 11 47 26" width="675" src="https://user-images.githubusercontent.com/86378921/194628929-d7227696-8711-4718-b624-8c545250715e.png">

@shelaghm 
Error text uses `TextAppearance.Material3.BodySmall` typography style, and top margin is 4dp.
For screenshots, please refer below link
https://github.com/google/android-fhir/pull/1655#issuecomment-1271198931

**Comment by shelaghm** [comment]
@santosh-pingle thanks for confirming the typography style. That is the correct one. I think we can mark the padding issue as resolved for this. 

@jingtang10 @santosh-pingle what about error message **placement** for single/multiple/other choice? Happy to create a new issue if that's better.

**Comment by jingtang10** [comment]
thanks shelagh and santosh - i think we're clear now.

the error message below text input has always been fine (4px). the issue in this issue is with single choice (and the same problem with multiple choice).

what should the paddings be if the error is on top?

**Comment by jingtang10** [comment]
Let's keep the discussion in the issue itself and only talk about actual implementation in the PR 1655.

Shelagh - a couple of questions:

1. if we move this error message above the radio buttons for single choice widget (and assuming that's the same for multiple choice and boolean choice widgets since the layouts are very similar), there is a potential inconcsistency of the location of the error message with other types of widgets we have that are using a single text field. according to material design they have the error text just below the text field. is this inconsistency justified by the fact that in single choice, multiple choice and boolean choice widgets we have multiple options? are we ok with this inconsistency?
2. just to note that the instruction text may not actual be "select one" or "select multiple" or anything of that effect. it could be something totally different because this is specified by the questionnaire author. in those cases, are we still ok to place the error message right below it, since it might be less connected to the instruction text.

having looked at the screenshots in 1655 again, maybe 4dp below the last radio button is ok... i was just worried that it looked too close. @shelaghm please will you please make the call here?

**Comment by shelaghm** [comment]
@santosh-pingle @jingtang10 I think the 4dp padding looks good on the radio button. It is consistent with M3 guidelines, so let's keep this as Santosh has implemented and not make further adjustments on the padding.

1. Very valid point on the inconsistency. As you mentioned in 1655, there's two different widget types and I recommend we keep error messages as is for text based entry as these are standard. My primary concern is A) the error message placement is directly tied to the last radio/checkbox option for boolean, single and multiple choice and B) that the error message might be hidden below the fold (example: there's 6+ options in a list and person is using a small screen size) and people don't see the error message at all. 

Why is this okay to be inconsistent here? 

- These widget types already look different from text entry/date/dropdown and can take up a lot more space and go below the fold.
- The error message applies to the whole component group and not just one individual checkbox/radio button. 
- Worst case scenario is that a user might not see the error message if it is at the bottom of the last option displayed

2. Yes, good point. I mocked up an example where the text is more lengthy, so we can see what it looks like and I still think the error message text is more discoverable higher up on the page before all the options are displayed.  

3. We also have other methods of showing an error, which is why the outline/stroke of the checkbox/radio button is red when there's an error, so we are not just reliant on the error message itself. This might also help in this scenario. (see screenshot below)

4. Regarding issue A. Google forms has an error message at the bottom, but it looks like it is grouped with the whole question, not one checkbox/radio button. (attaching screenshot below)

5. I found an old mockup where the error typography is the same and it makes it look more cohesive and doesn't feel that inconsistent that the location differs.
<img width="410" alt="Screen Shot 2022-10-11 at 15 04 15" src="https://user-images.githubusercontent.com/86378921/195207004-f83a5ef1-d656-453b-b03f-bbad7fb28f94.png">

Mockup w/ long instructions
<img width="1173" alt="Screen Shot 2022-10-11 at 14 39 32" src="https://user-images.githubusercontent.com/86378921/195204629-9437709f-70d8-404f-b54b-910e87bdc625.png">

Google form
<img width="498" alt="Screen Shot 2022-10-11 at 14 56 39" src="https://user-images.githubusercontent.com/86378921/195206285-22a6e511-ec51-44ec-8c2f-85b7b88ffd89.png">
