### ISSUE TITLE
Date picker validation accepts nonsensical answers

### ISSUE THREAD

**Issue by williamito** [google/android-fhir#1638]
**Describe the bug**
I can type invalid dates into the Catalog app like `40/0/2` into the date picker with no validation error.

**Component**
SDC Library / Catalog

**To Reproduce**
1. Open a questionnaire with a datepicker, e.g. Catalog app which says it wants `M/d/yy`
2. Enter `40/0/2`

**Expected behavior**
Nonsense values should not pass validation

**Screenshots**

https://user-images.githubusercontent.com/7772901/192644308-f062952f-1c4a-40bc-bba6-6e8b50aff921.mp4

**Smartphone (please complete the following information):**
 - Device: Any

**Additional context**
`40/0/2` seems to translate to `4/2/05` if you tap the calendar icon?

**Comment by omarismail94** [comment]
I can take a look at this!

**Comment by omarismail94** [comment]
@shelaghm @williamito proposed fix in PR #1687 


Copied the description from the PR below as to what the issue was:
By default, the [DateFormat.parse](https://developer.android.com/reference/java/text/DateFormat#parse(java.lang.String,%20java.text.ParsePosition)) method parsing is lenient: If the input is not in the form used by this object's format method but can still be parsed as a date, then the parse succeeds.

So in the case of 40/0/2, with leniency set to true, it would convert this to March 31, 5. Not 2005. 05. FIVE! Mind blowing haha. I didnt dig into the implementation, but I assume it does 2 + 40//12 = 5 for the year, and then the remainder becomes the month and day.
