### ISSUE TITLE
SDC: Single Choice question unselects the selected answer

### ISSUE THREAD

**Issue by nsabale7** [google/android-fhir#1640]
**Describe the bug**
Question with type as single choice unselects its answer when switched between two same answer options.
This is similar to #1521.

**Component**
SDC library

**To Reproduce**
 1. Open Catalog app
 2. Click on Single choice
 3. Select first answer option -> switch to second answer option -> switch again to first answer option -> switch again to second answer option
 4. Answers gets unselected 

**Expected behavior**
Second option should be selected

**Screenshots**

https://user-images.githubusercontent.com/82660329/192847210-f9b541c4-e63e-467c-94e0-b7f5332147cf.mp4

**Smartphone (please complete the following information):**
Device: Pixel4a
Android version: 12

**Comment by joiskash** [comment]
cc: @jingtang10 Please have a look at this, I think its an important one

**Comment by jingtang10** [comment]
While toggling the single choice options, sometimes the `bind` function in the view holder will be called. This is not expected. When we update the answer the newly generated view items should be considered the same content as the old view items, and therefore the recycler view item does not need to be rebound.

I thought when we disabled item animator in recycler view this problem should have been resolved. But it seems that's not the case.

@yigit when the adapter considers the new item to be the same item as the old one, does it keep the new one around or discard it? It seems to me that it does keep the new one around. This is undesirable behavior for us.

**Comment by jingtang10** [comment]
the comparison is here: https://github.com/google/android-fhir/blob/e878ad41e3e368d8da16307f229440db90c46807/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemEditAdapter.kt#L198

**Comment by jingtang10** [comment]
discussed with @yigit.

the issue is that when we skip binding of new data item because they're the same, recycler view is still only aware of the new item (it doesn't own the data at all) but the ui still has references to the old item.. so when we compare items again, the new item will be used.

this is an extremely tricky issue to solve with ui inputs. but what we should do is:

1. stop updating the answers (which is a copy of the answers in the questionnaire response in the view model) in the questionnaire item view item... the backing data for recycler view should be immutable. when the user inputs an answer, the answer should be updated directly in the view model via the callback. this will then result in ui update because the new answer will not match the old answer.
2. update widgets so that we only update UI widgets lazily. we already do this to an extend. for example, if the answers are not changing, we should not update the input widgets.
