### ISSUE TITLE
Support for Extension: Answer Options Toggle Expression

### ISSUE THREAD

**Issue by parthfloyd** [google/android-fhir#1773]
**Is your feature request related to a problem? Please describe.**
This extension is useful when A question has a list of possible answers but the list to be actually displayed depends on the previous question.

**Describe the solution you'd like**
This extension solves this use case.

**Additional context**
[HL7 answerOptionsToggleExpression Extension Link](https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-answerOptionsToggleExpression.html)

cc: @jingtang10

**Comment by KhumboLihonga** [comment]
@parthfloyd @jingtang10 Just flagging this issue as a feature we need for our app.

USE CASE:
We have a questionnaire known as 'Counseling' and in this questionnaire, different counseling messages are presented based on the age of the patient. A `choice` item is used to list out the counseling messages and the user is meant to select which message they provided to the client. See the screenshot [attached](https://user-images.githubusercontent.com/90775548/226612770-84782b31-a48f-47e3-9377-6aa30a81e24b.jpg).

However, without this expression, it means we need to create multiple `choice` items per age range. As you can imagine, this makes the questionnaire difficult to manage. In addition, unlike the example provided [here](https://build.fhir.org/ig/HL7/sdc/examples.html#answerOptionToggleExpression), it would be better for our implementation to hide the options as opposed to disabling them. As a result, each answer option will be evaluated against a FHIR path expression that determines whether the option should be shown or not.

Let me know what you think.

**Comment by KhumboLihonga** [comment]
@FikriMilano yes, after reviewing this [example](https://build.fhir.org/ig/HL7/sdc/examples.html#using-answeroptiontoggleexpression), you are correct on this. However, our use case would require the option to be hidden as opposed to being disabled but still use fhir path to toggle the options. Could you advise what the recommended approach to do this would be?

**Comment by FikriMilano** [comment]
@KhumboLihonga I can't find a way without breaking your requirement.
If it was me, I'll just use enable when expression and check the Patient age using FHIRPath.

> it means we need to create multiple choice items per age range

**Comment by KhumboLihonga** [comment]
Duplicating items and using enable when expression to solve this problem is fine when it is a simple scenario e.g. one item for male options and one item for female options. However, when you start to factor in date ranges for instance, it gets very difficult to maintain e.g. for an item that records a phone owner (mother/father/spouse/other/self), a patient who is under 15 years may have one set of options; a patient between 15 and 18, another set of options; and one over 18 years, their own set of options. Combine that with recording multiple phone numbers, it gets quite messy.

I understand that the FHIR spec stipulates the disabling of the options but it also has a number of challenges:
1. The user doesn't need to see options that they will _never_ select - it's an unnecessary cognitive load on the user. For example, it is unnecessary for a user to see options about pregnancy or breastfeeding for a male patient.
2.  For a long list of options, it would be better to just filter out the unnecessary options as opposed to disabling them. For example, a dropdown item listing all the different medications that can be administered can be over 100 options long as it varies across ages.

Overall, in our use cases, we can't think of many scenarios where we would rather disable an option instead of hiding it - if the user shouldn't select it, then they shouldn't see it. Given the above challenges, I'm wondering if we can include hiding the options as part of this ticket. What are your thoughts? @FikriMilano

cc @Gental-Giant

**Comment by FikriMilano** [comment]
I can think of 2 options:
1. To make it configurable in the SDK, whether to enable/disable or show/hide
2. @KhumboLihonga needs to submit a proposal to FHIR to update the functionality of the answerOptionsToggleExpression extension itself or to introduce a new extension w show/hide functionality for a given answer option, but I recommend you to have a chat w them first, via FHIR Zulip Chat perhaps

what do you think @jingtang10?

**Comment by KhumboLihonga** [comment]
@FikriMilano That's fine with me and sounds like a good idea. I can ask and see what response I get on the FHIR Zulip Chat before making any formal proposal.

**Comment by KhumboLihonga** [comment]
I posted to the Zulip chat and got a response from them. They mentioned that the spec isn't clear about 'disabled' meaning that it is either greyed out or hidden. But they also went on to suggest having another extension that toggles this behavior. You can view the discussion [here](https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/answer.20options.20toggle.20expression/near/360861623).

@FikriMilano @jingtang10 how do you propose we proceed?

**Comment by KhumboLihonga** [comment]
Just following up on this. Since the discussion established that "disabled" can mean either "greyed out" or "hidden", can we proceed with options being hidden? We can loop in the design team too for confirmation but I believe hiding the answer options will be a more common use case.

Then afterward, work on an additional extension can be done to toggle whether the options should be hidden or disabled.

@FikriMilano @jingtang10 what do you think?

**Comment by FikriMilano** [comment]
@pld @rowo @f-odhiambo 
Let me know what you think

**Comment by jingtang10** [comment]
With the spec not being prescriptive on how we handle "disabled" (i.e. hidden or greyed out), I'm ok with the android fhir SDK sdc library taking either one of the two approaches.

Personally I think hidden is fine. We don't need to confuse the user with a lot of greyed out options.

Fikri - are you saying that you need the options to be greyed out? If not, let's go with hidden.

**Comment by FikriMilano** [comment]
Personally I'm fine with hidden and/or greyed out, I can see how we might use either at some point.

Currently I'm waiting for a response from my design team whether changing the initial plan in our use case, from greyed out to hidden is ok.

**Comment by FikriMilano** [comment]
@jingtang10 @KhumboLihonga
My design team said it's ok to use hidden :D
I think we are free to proceed w the ticket

cc @rowo @f-odhiambo

**Comment by jingtang10** [comment]
Excellent thanks Frkri.

Is anyone able to spend some time and send a PR?

**Comment by KhumboLihonga** [comment]
@jingtang10 yes, @LZRS will be working on this ticket.

cc @Gental-Giant

**Comment by FikriMilano** [comment]
@LZRS any updates on this? Feel free to ask if you need any support

**Comment by LZRS** [comment]
What should happen in a scenario whereby the resolved answerOptionsToggleExpression results to an empty list of answerOptions for a required field? I'm not sure how to handle that

**Comment by FikriMilano** [comment]
@LZRS 
We can treat it as an error during validation or ignore any non-available options.
We have 2 options, what do you think @jingtang10?

According to FHIR spec:
https://build.fhir.org/ig/HL7/sdc/expressions.html#answerOptionToggleExpression
> The base set of options available comes from [answerOption](https://build.fhir.org/ig/HL7/sdc/behavior.html#answerOption), [answerValueSet](https://build.fhir.org/ig/HL7/sdc/behavior.html#answerValueSet) or [answerExpression](https://build.fhir.org/ig/HL7/sdc/expressions.html#answerExpression). If any of the options listed in the option component of this expression is not one of the options available for the item, then that SHOULD be treated as an error in the Questionnaire when validating the Questionnaire. However, when completing forms it is safe to ignore any non-available options.

**Comment by jingtang10** [comment]
i don't think we need to do anythign special in this case - sometimes a questionnaire cannot be complete and the application needs to handle it to save a draft.

**Comment by FikriMilano** [comment]
Thanks @jingtang10 👍
Hope that's clear @LZRS
