### ISSUE TITLE
Repeated Group: Answers within group are not present in the QuestionnaireResponse, if child question depends on enableWhen condition of another child question

### ISSUE THREAD

**Issue by nsabale7** [google/android-fhir#1776]
**Describe the bug**
Suppose a child question depends on enableWhen condition of another child question and both the questions are part of repeated groups, answers are not present in the QuestionnaireResponse for the question which depends on enableWhen condition.

**Component**
SDC library

**To Reproduce**
Use [test-questionnaire.txt](https://github.com/google/android-fhir/files/10284902/test-questionnaire.txt) as questionnaire json.

https://user-images.githubusercontent.com/82660329/209086244-0d64468c-d58a-46aa-9fc8-674cd584a930.mp4

@jingtang10

**Comment by jingtang10** [comment]
fyi @kevinmost

**Comment by joiskash** [comment]
http://community.fhir.org/t/questionnaire-repeating-groups-what-is-the-correct-format/2276/3

**Comment by joiskash** [comment]
The implementation currently adds answers to item.answer for repeated groups, and then later createRepeatedGroupResponse takes care of putting answerItemComponents to the repeated groups item.item field.
While writing the UT I have set the initial answer of the child question of the repeated group. But the code that populates questionnaireResponse with initial answers adds the answer of the repeated groups in item.item , so this results in createRepeatedGroupResonse returning an empty list, since it cannot find any answers in the item.answer field.

Suggested change : Initial answer for repeated groups should be set in the item.answer field so that it is consistent with the rest of the repeated group flow.

cc: @jingtang10 @kevinmost

**Comment by nsabale7** [comment]
This issue has been resolved. There is a new issue related with this #1895.
