### ISSUE TITLE
Catalog application is stuck when submit button is clicked for Attachment response.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1823]
**Describe the bug**
In catalog app, captured response json is shown on the screen when user click on submit button.
If attachment size is more than 500 KB then application get stuck when user click on Submit button.

**Component**
reference app, or SDC gallery app

**To Reproduce**
1. Go to Catalog app
2. Click on attachment component
3. Click on Take Photo 
4. Photo get uploaded to the attachment.
5. Click on Submit button
6. See catalog app get stuck and then exits 

**Expected behavior**
Application should not be stuck.
May be attachment binary data can be skipped when response json get shown in the form of text on the screen.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4
 - Android version: Android 12

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@shelaghm @FikriMilano

**Comment by shelaghm** [comment]
@santosh-pingle can you say more about this? 

My understanding is that
- It seems like this error shouldn't happen and that we should fix this bug
- If we can't fix the issue, we could show an error message so that people know what's causing the app to get stuck?

Did you have something else in mind?

**Comment by FikriMilano** [comment]
@santosh-pingle 
Correct me if I'm wrong, but this likely happens because the questionnaire response contains an attachment binary that is too large.
Even if you're not trying to display the attachment binary in a text after submission, the issue still happens.

This ticket should resolve this issue: https://github.com/google/android-fhir/issues/1858
