### ISSUE TITLE
Bottom container style and behavior customization

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#1842]
**Is your feature request related to a problem? Please describe.**
The current submit button container at the bottom of the screen, has no shadow at the moment.

FHIRCore has a UX design update that requires the submit button container to have a shadow in the upward direction when there’s content below it, and just a border line at the top if there's no content below it, i.e. at the end of the list.

**Describe the solution you'd like**
The bottom submit button container should display a shadow at the top side if there's content below or just a border line if there's no content below.

**Describe alternatives you've considered**
Configurable?

**Additional context**
This is related to the UX Questionnaire adjustments that is ongoing on FHIRCore https://github.com/opensrp/fhircore/issues/1974.

Adjusted design:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/4540684/213273444-f3fe9b1a-2e80-46ab-baa0-7fcdd8302313.png">

**Would you like to work on the issue?**
Yeah

**Comment by FikriMilano** [comment]
cc @f-odhiambo

**Comment by FikriMilano** [comment]
@shelaghm what do you think of this UX change?

cc @rowo

**Comment by shelaghm** [comment]
Hi @FikriMilano @rowo 

We are currently supporting Material 3 design system on the FHIR SDK and the latest [material.io guidelines](https://m3.material.io/components/top-app-bar/overview), indicate 
> Instead of elevating with a drop shadow, top app bars use a color fill to create separation from content

I understand that your design system leverages drop shadows throughout the application and your desire to continue to do so. I'm not opposed to making something like this configurable, but we are trying to be conscious of how many different elements become configurable, while also following the latest Material theming patterns and behavior. @jingtang10 what are your thoughts on this?

@rowo Are you currently using the material [theme builder](https://m3.material.io/foundations/customization#94cc449c-950f-4a08-99ab-ca0ae27bfc1f) and tokens? Any plans for adapting your design system in the future? Asking because it will be helpful to understand how critical the drop shadows are?

**Comment by FikriMilano** [comment]
@shelaghm sorry, I think there's a bit misunderstanding here.

I was implying the container of `Save` button, at the bottom of the screen. There's a shadow there.

Not the top app bar.

**Comment by shelaghm** [comment]
@FikriMilano Ohh, yes, I misunderstood. Thanks for clarifying. 

Yes, I think this can be configurable. Some of the options I imagine are: 
<img width="939" alt="Screenshot 2023-02-03 at 15 05 46" src="https://user-images.githubusercontent.com/86378921/216727521-2c8ad609-7289-42a0-92af-8790fefd3f1b.png">

Some implementation suggestions: 
  - In the material theme: can use the `outline` color. 
  - There's pre-set [elevation tokens](https://m3.material.io/styles/elevation/tokens) that you can use. `Elevation #2` is probably a good option to start with.

**Comment by FikriMilano** [comment]
@shelaghm this image is very helpful, and thanks for the suggestions!
