### ISSUE TITLE
Prefill the questionnaire with an optional questionnaire response as an argument to the questionnaire fragment

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#189]
This can be used to pre-fill the questionnaire while generating the UI.

**Comment by joiskash** [comment]
#227

**Comment by joiskash** [comment]
> The order of questions within groups, groups within groups and groups within questions is relevant and must be retained for display and capture. The hierarchy items within the Questionnaire SHALL mirror the hierarchy of the corresponding Questionnaire (if any).

This allows us to assume that the QuestionnaireResponse structure will be corresponding to the Questionnaire from which it is derived. If there is a mismatch in the hierarchy the SDK will throw an error since in the context of SDC, the QuestionnaireResponse will always have a corresponding Questionnaire

**Comment by joiskash** [comment]
@jingtang10 so the plan is to 

1. Introduce `val questionnaireResponseJson` in the gallery\QuestionnaireViewModel
2. Pass the `questionnaireResponseJson` as `String?` since it is optional to the Fragment `arguments`
3. In datacapture\QuestionnaireViewModel introduce a `private fun Questionnaire.validateQuestionnaireResponse( questionnaireResponse : QuestionnaireResponse  )` which will check and make sure that the hierarchy items within the Questionnaire SHALL mirror the hierarchy of the corresponding Questionnaire. 
What exception should be thrown if there is a mismatch in the structure?
4. In the second init block in datacapture\QuestionnaireViewModel I will introduce a check and see if `state["QuestionnaireFragment.BUNDLE_KEY_QUESTIONNAIRE_RESPONSE"]` not null then parse the `questionnaireResponseJson `and get the object `questionnaireResponse`
5. `questionnaireResponseBuilder.addAllItem(questionnaireResponseJson.itemList)` instead of the `foreach` block

**Comment by jingtang10** [comment]
thanks @joiskash.

so in step 4 you will use the validate method if a questionnnaire response is provided right?

So basically, if there is a questionnaire respoonse provided, validate it, if not, create a new one mirroring the structure (existing code).

**Comment by joiskash** [comment]
> 
> 
> thanks @joiskash.
> 
> so in step 4 you will use the validate method if a questionnnaire response is provided right?
> 
> So basically, if there is a questionnaire respoonse provided, validate it, if not, create a new one mirroring the structure (existing code).

Yes that's right

**Comment by joiskash** [comment]
@jingtang10  If the structure of the questionnaire response provided does not match the questionnaire then should the library throw an error? or just warn the user? 
And what error should be thrown if any?

**Comment by jingtang10** [comment]
I would rather for the library to throw an illegal argument exception than to swallow that issue.

**Comment by joiskash** [comment]
While validating is it fair to say that the order of the occurrence of item in the questionnaire will be the same in the questionnaire response? 
eg if in the json string of the questionnaire linkid 1 is followed by 2 and in the json string of the questionnaire response linkid 2 is followed by 1.  Should this throw an error or is this acceptable?

**Comment by jingtang10** [comment]
I don't think this is acceptable. The order should be maintained too in the
questionnaire response structure.

Jing Tang |  Senior Software Engineer |  jingtang@google.com |  +44 (0)7872
645655

**Comment by jingtang10** [comment]
@joiskash can this be closed or is there something else you're still working on?

**Comment by joiskash** [comment]
This can be closed thanks :)

**Comment by jingtang10** [comment]
thanks and well done for resolving this issue.
