### ISSUE TITLE
Repeated Group: Items within group are duplicated in the Questionnaire Response, if question depends on enableWhen condition.

### ISSUE THREAD

**Issue by nsabale7** [google/android-fhir#1895]
**Describe the bug**
If a question depends on enableWhen condition in a repeated group, it duplicates the items from the first response.

**Component**
SDC library

**To Reproduce**
Use [component_repeated_group.txt](https://github.com/google/android-fhir/files/10871700/component_repeated_group.txt) as a questionnaire

**Screenshots**
https://user-images.githubusercontent.com/82660329/222439586-5edfd017-31bb-485b-88d3-622de7b0a80e.mp4

@jingtang10

**Comment by santosh-pingle** [comment]
looking into it, thanks!

**Comment by santosh-pingle** [comment]
In the `QuestionnaireviewModel`,  `getEnabledResponseItems` API does not filter items correctly. It appears that the 'evaluate()' API is returning a false value for enabled items as well.

**Comment by santosh-pingle** [comment]
If you refer the attached video for steps : 
In the second repeated group item, the evaluate() function returns true for the 12.6.3 item and false for the 12.6.4 item. Expected return value should be true for 12.6.4 and false for 12.6.3.

**Comment by santosh-pingle** [comment]
According to the existing code, the EnablementEvaluator class has a `questionnaireResponseItemPreOrderList` that stores collections of responseItemComponents. If the type is a repeated group item, then the questionnaireResponseItem can have the same linkId if the repeated group is added more than once.
When the `evaluateEnableWhen()` API is called to check whether the enable_when_constraint is passed for a questionnaire response item, it fails for the second and subsequent response items.
This is because the `findEnableWhenQuestionnaireResponseItem()` function always returns the first item that matches the link id, causing the `evaluateEnableWhen()` API to fail for the second and subsequent response items that have the same link id.

**Comment by santosh-pingle** [comment]
Additionally,
if type is repeated group item then `questionnaireResponseItemParentMap` is always empty, it is observed/checked when findEnableWhenQuestionnaireResponseItem() api is called to get the target response item of enable question. This is  because the `questionnaireResponseItemParentMap` is never built up, the logic of `buildParentList` in `EnablementEvaluator` fails for repeated group type.
