### ISSUE TITLE
Update the purge API to accept a list of resource IDs

### ISSUE THREAD

**Issue by dubdabasoduba** [google/android-fhir#2439]
**Is your feature request related to a problem? Please describe.**
- We would like to be able to purge resources in bulk selectively.  This would help implement functionality to delete data tied to certain jurisdictions if a user stops being responsible for that jurisdiction. 
- Example: - A practitioner is assigned to collect data for Nairobi but is then transferred to Mombasa. We would like to have the ability to purge the Nairobi "patient" data. 
- The current purge API expects 1 resource ID at a time. This ticket is aimed at updating that to expect a list of IDs

**Describe the solution you'd like**
- [ ] The suggested solution by @aditya-07  is to combine the Search and Purge API i.e. search for the resources to delete using the relevant resource search parameters then pass the result result resource IDs to the purge API for deletion.

**Comment by MJ1998** [comment]
Thanks Benjamin,
This seems to be correctly captured. 
@aditya-07 To take over from here!

**Comment by jingtang10** [comment]
@dubdabasoduba @f-odhiambo @ndegwamartin can you please propose someone to work on this? thanks!

**Comment by ndegwamartin** [comment]
@jingtang10 @aditya-07 in the context of this change, had a few points for clarification.
 1. Since we are in v1.0.0 of the Engine module and this is a breaking change - do we mark the `FhirEngine.purge` and the `Database.purge` as _deprecated_ or should we overload the method?
 2.  Since the plan is to iterate through the list of ids in the Database.Purge, how should we handle cases where processing of individual ids fail? i.e. should we let the ones that pass the checks purge successfully or should we consider processing the whole list a transaction?

**Comment by ndegwamartin** [comment]
Based on earlier discussions:
1. I've overloaded the `FhirEngine.purge` and modified `Database.purge` since has access modifier `internal` which is reused by the FhirEngine overloads.
2. I've wrapped the whole list in a transaction

PR linked here https://github.com/google/android-fhir/pull/2462 . We can iterate on any feedback

**Comment by dubdabasoduba** [comment]
> Since the plan is to iterate through the list of IDs in the Database. Purge, how should we handle cases where the processing of individual IDs fails? i.e. should we let the ones that pass the checks purge successfully or should we consider processing the whole list as a transaction?

@ndegwamartin I think we should let the resources that pass the checks purge successfully. We can ensure the SDK reports the resources that failed to purge so the implementing apps know how to handle the failures.

**Comment by ndegwamartin** [comment]
@dubdabasoduba after the conversation today we've agreed to wrap the whole batch list processing logic in a transaction. Thus if any item fails it throws an `IllegalStateException`. cc @MJ1998
