### ISSUE TITLE
'SELECT' queries sometimes take too long to run 

### ISSUE THREAD

**Issue by LZRS** [google/android-fhir#2552]
**Describe the bug**
Running a simple GET query through `FhirEngine#get`  sometimes takes too long.
After some tests, it seems it may be caused by the query having to wait for other queued transactions to complete for it to run. This seems to be because the 'SELECT' queries similar to other CRUD operations in Database [implementation](https://github.com/google/android-fhir/blob/8e2aaf0002c8a75eb0e74665480aa552b9876580/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt#L176) are wrapped in a [Transaction](https://developer.android.com/reference/androidx/room/Transaction).

From the [docs](https://developer.android.com/reference/androidx/room/Transaction)

> Room will only perform at most one transaction at a time, additional transactions are queued and executed on a first come, first serve order

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by MJ1998** [comment]
This is less likely and in case it is I am not aware of any solution.
Could it be because you are calling `FhirEngine.get` on UI thread ?
May be try wrapping your call with `withContext(Dispatchers.IO) { }`

**Comment by MJ1998** [comment]
@yigit Need your help here

**Comment by MJ1998** [comment]
From discussion with @yigit, this particular read api should be executed independently of any transaction.

Reason (in Yigt's words): The transaction you add there doesn't really help with anything because you are only doing a read inside that transaction and it is a single read. SQLite will already do a "read transaction" for it implicitly, which will make that consistent.

Would you like to work on this @LZRS ?
