### ISSUE TITLE
Helper function to match the correct pair of qItem and qrItem

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2618]
```
val qrItem = questionnaireResponse.allItems.find { qrItem -> qrItem.linkId == qItem.linkId }
```

this can get quite complicated in the world of nested items and nested repeated groups because link ids no longer uniquely identify a questionnaire item or a questionnaire response item...

i've been meaning to write a helper function that traverses the two trees in parallel and match the pairs.. maybe it's time for me to do that..

_Originally posted by @jingtang10 in https://github.com/google/android-fhir/pull/2522#discussion_r1671170333_

**Comment by jingtang10** [comment]
i'll take this

**Comment by allan-on** [comment]
Hello @jingtang10 @FikriMilano I think the changes introduced here through the associated PR are backwards-incompatible. 
This [requirement](https://github.com/google/android-fhir/blob/01cc80a8dc696c90a2b7f1ee6d78068276ffd17f/datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaires.kt#L202) fails where 
a. The questionnaire items nested under the repeated group are not represented as answer components in the questionnaire response and
b. The **number of questionnaire items isn't equal to the number of questionnaire response items** because for instance, a questionnaire item didn't have an answer because it was optional or it was hidden by an `enableWhen` expression

**Comment by jingtang10** [comment]
> Hello @jingtang10 @FikriMilano I think the changes introduced here through the associated PR are backwards-incompatible. This [requirement](https://github.com/google/android-fhir/blob/01cc80a8dc696c90a2b7f1ee6d78068276ffd17f/datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaires.kt#L202) fails where a. The questionnaire items nested under the repeated group are not represented as answer components in the questionnaire response and b. The **number of questionnaire items isn't equal to the number of questionnaire response items** because for instance, a questionnaire item didn't have an answer because it was optional or it was hidden by an `enableWhen` expression

See https://build.fhir.org/questionnaireresponse.html#link.

My understanding of the spec is that the questionnaire response really should be structurally consistent with the questionnaire. Hidden questions are just hidden, they should still be there. Same thing with questions that are not answered or not answered yet.

Please share your questionnaire and questionnaire response and we can have a look what exactly is the problem here.  Thanks!
