### ISSUE TITLE
Use integer or real as the data type for number index

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#283]
At the moment we use BigDecimal stored as strings in the database number index tables: https://github.com/google/android-fhir/blob/master/core/src/main/java/com/google/android/fhir/db/impl/DbTypeConverters.kt#L51

This defeats the point of having number index. We should change the underlying data type to be integer or real (sqlite data type for decimal). It's not clear to me if we should create a separate integer index table or just put everything in the real index table.

**Comment by kevinmost** [comment]
There are two possible approaches here, each with their own pros and cons:

---

### Use REAL for numeric indices

Just change the `BigDecimal` <> `String` conversion to a `BigDecimal` <> `Double` conversion.

Pros:
- Super-simple change, easy to maintain
- More performant

Cons:
- Numeric range is lost (minor issue, as Double.MAX_VALUE is quite large)
- Accuracy is lost
  - In particular, this is concerning because two numbers could round off to the same floating-point representation
  - When doing a sorted `LIMIT 1` operation, for example, this could result in undefined behavior for retrieving the largest/smallest value that matches a search query
 

---

### Use an int + string

`BigDecimal` is represented by two values: An `int scale` and a `String unscaledValue` (it's actually stored as an `int[]`, but we'll use its `String` representation).

We can deconstruct the `BigDecimal` when we put it in the DB, into two separate columns.

To do this, we need to make a new class (eg, `FHIRBigDecimal`) and make it `@Embedded` into our Room Entities. ([read more](https://developer.android.com/reference/android/arch/persistence/room/Embedded))

This might be more complicated than we thought it'd be based on our last meeting, though. Edge-cases, eg negative numbers and decimals in the range `(-1, 1)` are tricky. I've tried to approximate how SQLite would sort these (by the "magnitude" of the int, then by the string representation of its unscaled value, lexographically) [here](https://pl.kotl.in/nOuNBsDWQ).

Pros:
- Perfect precision
- Unlimited range

Cons:
- Performance hit (sort using 2 fields, one of which is a string)
- More complicated

**Comment by jingtang10** [comment]
@brynrhodes @pld FYI

**Comment by jingtang10** [comment]
Just one minor correction: the int+string approach still have an upper bound of range - it's `10^(2^63-1)` because the int has an upper bound of `2^63-1`.

A third approach is to use one string field to encode the numbers lexigraphically while maintaining order: https://www.zanopha.com/docs/elen.pdf

**Comment by jingtang10** [comment]
Looking at these different approaches, I think personally I have a slight preference for using REAL for its simplicity.

If we change our mind in the future, we can always write a db migration.

How do others feel?
