### ISSUE TITLE
Rethink indexing date time with precision

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#433]
**Describe the issue to be researched**
Currently the in date index table we index the start and end datetime values as well as the precision.

**Describe the goal of the research**
Decide if the precision column is actually useful. I have the feeling that we probably should just index different start/end values depending on the precision at the point of indexing resources. Rather than keeping the precision column itself.

**Describe the methodology**
Understand the FHIR search standard esp. the date part: https://www.hl7.org/fhir/search.html#date
Research the internal representation of the HAPI FHIR lib we use

**Would you like to work on the issue?**
Happy to collab.

**Comment by jingtang10** [comment]
@deepankarb fyi

**Comment by epicadk** [comment]
Yes instead of indexing the precision we should add the precision to ts_high. For instance, if the date is 2001-09-08 then we should index ts_high as 2001-09-09 and ts_low as 2001-09-08 as explained in the example given [here]( https://www.hl7.org/fhir/search.html#date). This probably should have been done in #332 but I guess I missed this 😓.

**Comment by epicadk** [comment]
Can I open a pr with what I have in mind? We can discuss further on the pr?
