### ISSUE TITLE
Some values in StringIndexEntity table is recorded as a ClassName@MemoryLocation

### ISSUE THREAD

**Issue by rkodev** [google/android-fhir#450]
**Describe the bug**
Some values in the `StringIndexEntity` table e.g Patient.name and Patient.address value are stored as the dafault Java `toString()`  value i.e a ClassName@MemoryLocation

**Component**
Core library,

**To Reproduce**
1. Sync data using Data Capture Gallery
2. View data stored in `fhirEngine` database `StringIndexEntity`  `index_path` = `Patient.name` 

**Expected behavior**
Expecting the column to store a combination of the Patient's names

**Screenshots**
N/a

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Would you like to work on the issue?**
open to it

**Comment by epicadk** [comment]
Can you update the issue so that it reflects a similar issue with Patient.address?

**Comment by rkodev** [comment]
@epicadk done

**Comment by epicadk** [comment]
Thanks @rkodev , are you working on this? It's related to an issue I am working on so if you aren't I could fix this.

**Comment by epicadk** [comment]
Continuing [this discussion](https://github.com/google/android-fhir/pull/464#discussion_r630950722) here. I think it won't make sense to join the name as one string. We could rather index the name part by part i.e. add each prefix , given , family name to the index separately.  

This can be improved further because the given and family names of a patient are indexed separately (patient.name.given & paitnet.name.family search param) .

**Comment by jingtang10** [comment]
@epicadk We already have the separate indices e.g. `given` or `family`. But we also need this `patient.name` index because the user might search for a string and that could be in the given or family name. It'll be unnecessary to require the user to compose a search query by using `patient.given` and `patient.family` when `patient.name` suffices.

**Comment by epicadk** [comment]
> @epicadk We already have the separate indices e.g. `given` or `family`. But we also need this `patient.name` index because the user might search for a string and that could be in the given or family name. It'll be unnecessary to require the user to compose a search query by using `patient.given` and `patient.family` when `patient.name` suffices.

I was suggesting something like 

    fun StringFilter.query(type: ResourceType): SearchQuery {
      if (parameter == Patient.NAME){
       return SearchQuery("SELECT resourceId From StringIndexEntity where resourceType = ? AND (index_name = ? or index_name = ? ) AND index_value like '%' || ? COLLATE NOCASE", 
              listOf(type.name,Patient.GIVEN,Patient.FAMILY,value!!))
      }
    // Handle rest of the cases normally
    }
    

I think this would avoid data duplication. 

- [ ]

**Comment by epicadk** [comment]
If we use the current approach which is to store then as a concatenated string, we would have to make use of wildcards both at the beginning and the end of the query (something like `index_name LIKE '%eve%'` however this cannot make use of the indexes so the query may take longer.

**Comment by jingtang10** [comment]
Thanks @epicadk for the comments. For a full name search, for example "Aditya Kurkure", the search API should return a result. If we store everything entirely separately, it's more difficult (still possible, but the SQL query would be far more complex) to return the right result.

I do think name search would probably be often used in conjunction with "contains" rather than default match (match the beginning) or exact match.

Seems like that's slightly beyond the scope of this issue - do you want to create a new issue and add the descriptions of the problems we have discussed here?

**Comment by epicadk** [comment]
> Thanks @epicadk for the comments. For a full name search, for example "Aditya Kurkure", the search API should return a result

Actually I tried this on the hapi fhir server and it doesn't. It only matches to given, ,family ,prefixes, suffixes, text individually. It does not use any concatenation. 
For example, If the given name was Aditya and the family name was Kurkure then searching for Aditya kurkure would not match.

> Seems like that's slightly beyond the scope of this issue - do you want to create a new issue and add the descriptions of the problems we have discussed here?

I agree the issues are not evident during indexing but you can see them while implementing string search. So I think we can include it in #426  ( I have made some changes to the indexing api already. If it's not something we need I'm happy to revert it back.)

**Comment by jingtang10** [comment]
> > Thanks @epicadk for the comments. For a full name search, for example "Aditya Kurkure", the search API should return a result
> 
> Actually I tried this on the hapi fhir server and it doesn't. It only matches to given, ,family ,prefixes, suffixes, text individually. It does not use any concatenation.
> For example, If the given name was Aditya and the family name was Kurkure then searching for Aditya kurkure would not match.

Interesting. The spec does say it's: A *server defined* search that may match any of the string fields in the HumanName, including family, give, prefix, suffix, suffix, and/or text...

Regardless of HAPI's implementation, if you're a developer using the search API and using the `Patient.NAME` param, what would you expectation be?

**Comment by jingtang10** [comment]
> I agree the issues are not evident during indexing but you can see them while implementing string search. So I think we can include it in #426 ( I have made some changes to the indexing api already to show what I was saying. If it's not something we need I'm happy to revert it back.)

Will comment in that PR but I don't think we have reached a concensus on this so to keep the PR simple I'd suggest not including this change.
