### ISSUE TITLE
Render questionnaire in different language using language extension

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#465]
**Is your feature request related to a problem? Please describe.**
Support for language extensions within a FHIR questionnaire

**Describe the solution you'd like**
- [x] When given a Questionnaire with different language extensions, be able to render in the appropriate language based on the Android language settings
- [x] If no language extension is available for the local language, show the default language (usually English) for the item
- [ ] Show related controls using the local language (from strings.xml) e.g. list selection options, back/forward (for multi-step questionnaire)

**Describe alternatives you've considered**

**Additional context**
Issue #161 has link to the updated Questionnaire with Vietnamese translations

**Would you like to work on the issue?**
Happy to support

**Comment by fredhersch** [comment]
See this issue #166 for discussion about implementing language support

**Comment by fredhersch** [comment]
@jingtang10 can we update this questionnaire in the SDC Gallery app and see this working?

**Comment by aditya-07** [comment]
@fredhersch I have already added the questionnaire in the SDC Gallery app and its available for everyone to checkout.

**Comment by jingtang10** [comment]
This isn't done yet as per @fredhersch's requirements:

- [ ] Show related controls using the local language (from strings.xml) e.g. list selection options, back/forward (for multi-step questionnaire)

Might create a new issue for that instead.

@pld raised a question about custom locale rather than using android system locale. After testing I realized you can set it by using `Locale.setLocale' API in your activity/fragment. So I think this is entirely doable by implementers with the current library following @aditya-07 's change.

**Comment by fredhersch** [comment]
@jingtang10 @aditya-07 I opened a new issue here - #503 503
