### ISSUE TITLE
Soft delete within the data access layer

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#471]
**Describe the issue to be researched**
Within healthcare apps, resources (like observations etc) are often considered immutable. Most relevant resources (like Observations) do not have a 'status'. If there is a desire to delete data, should we provide the option to do a soft delete.

Currently within the SDK, resources can be DELETED (using the data-access API).

To support SOFT DELETE, we would look to:

- Add 'flag' to the db for resources
- Within search results, by default only return resources where SOFT DELETE is NOT TRUE
- Provide additional search param for returning resources where SOFT DELETE is TRUE

**Describe the goal of the research**

- [x] Solicit input from implementer's on use cases to determine if resources are ever deleted
- [x] Determine if we should support the ability to SOFT DELETE a resource and filter it out of results

**Describe the methodology**
We will get input from the community of implementers who are best placed to help inform this. If there is a need for this functionality we will then determine the priority.

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
I think this issue is somewhat ameliorated by the fact that FHIR servers might implement soft delete, e.g., https://smilecdr.com/docs/fhir_repository/deleting_data.html. So if a resource is originated from the server side, deleting it on device will not remove the physical record on the server (although it won't show up in the search results from the server any more, you can still access the history of it by making specific queries listed in the aforementioned link).

On the other hand, if a resource is originated on the client side (e.g. a newly registered patient that hasn't been synced to the server), then not having soft delete will result in the record being permanently deleted.

**Comment by fredhersch** [comment]
Thanks @jingtang10. @joiskash , @pld or anyone else - any thoughts on this? Thanks.

**Comment by joiskash** [comment]
It will be a good feature to have and there is a current requirement to support soft delete in one of our projects. The project has a very simple uni-directional data flow. So to prevent the application from taking up too much space on the client phone we are implementing a soft delete. Just FYI we are not using the android SDK for this project.

**Comment by rkodev** [comment]
@jingtang10 One of the case where enabling a soft delete even when sync to the server has not happened would be in case where [Peer to Peer sync](https://github.com/google/android-fhir/issues/258) is enabled. 
A soft delete, will be required in order to propergate the delete action to the server and eventually to any device that may have offline shared data. 
If we iallow for P2P then a soft delete , at the very least for P2P shared data , will be required.

**Comment by fredhersch** [comment]
Thanks all for your comments. From reviewing the thread, we are proposing to mark this as a **'nice to have'** feature for the planned beta release (Q4 '21).

It will be good to flesh this out a bit further. Plan will be to create a new issue for this, specify the requirements and the prioritise for the post beta release roadmap.

I'm going to close the issue for now. If there are major objections, please let me know and we can reivisit. Thanks

cc: @pld @jingtang10 @joiskash @rkodev
