### ISSUE TITLE
Design & handing data conflicts in database on syncing

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#472]
**Describe the issue to be researched**
If there are data conflicts in the database - mostly due to sync issues - what are the patterns that we have (or should) implement to handle these? Specifically, if there are sync related issues, should these be able to be surfaced on the mobile device (i.e. via sync API).

Currently the approach is:
```
On sync:
* In the event of a disagreement between local update and server update:
* we currently try to apply local change on top of server change
```

**Describe the goal of the research**
- Validate the current approach to handling database conflicts via sync with implementers
- Identify any additional use cases and requirements for handling data conflicts
- Determine if there is a need to surface (via the SDK) data conflicts and if so, what would the requirements be

**What's the desired outcome of this task? What artifacts should be produced?**
Agreement on how we will support this. If there are additional requirements, these will be captured as issues and prioritised accordingly

**Describe the methodology**
- Solicit input from the community with discussion to be captured here
- We will aim for consensus. If not, we will bring this to the WHO technical calls for a final decision

**Would you like to work on the issue?**
Yes

**Comment by fredhersch** [comment]
Discussed on WHO technical WG2 call.

Discussed experience with different use cases from implementer's:

From @pld:
- General conflict issues don't happen very often with syncing between mobile and server
- Have had some experience with merging patient records which is related but different - would be worth creating a new issue on de-duplicating / merging issues

@litlfred Do you have some use cases that you can share here?

**Comment by fredhersch** [comment]
[SCD Type 2](https://docs.oracle.com/cd/E41507_01/epm91pbr3/eng/epm/phcw/concept_UnderstandingSlowlyChangingDimensions-405719.html) was proposed as an idea to look at:

**Comment by fredhersch** [comment]
@kaapstorm: suggested looking at Command Query Separation pattern. Changes are logged on the device and then replayed on the server which then creates the authoritative version. Please add additional comments

**Comment by kaapstorm** [comment]
Thanks @fredhersch (More context on [CQRS here](https://martinfowler.com/bliki/CQRS.html).)

I think a big consideration with this approach is its server-side requirements. I'm not sure these expectations would be practical.

Another issue that was raised about this approach is whether to trust device timestamps. An alternative is to use server timestamps at sync-time. That forfeits the ability to merge changes made on different devices at overlapping times, and will instead play all changes from one device over all the changes made on another device. But considering each user made the changes without being able to see the changes made by the other user, the risks are about the same regardless, and they are mitigated the same way:

As was discussed on the call, workflows to avoid conflicting changes could place more emphasis on an organisational solution rather than a technological one. Workflows can be designed in a way that avoids multiple users editing the same properties of the same resources -- even editing the same resource could be OK, if the users' responsibilities are separated and the properties they need to change are different. That will depend on how workflows are designed.

**Comment by pld** [comment]
For reference, OpenSRP handles conflicts in a number of ways, but it always stores a history of all versions and assumes the version with the greatest of an ordering field is the most recent version. In some deployments this ordering field is the server timestamp (eg assigned on sync). This is certainly not a good strategy if we are expecting conflicts, but they have been exceptionally rare.

We have other OpenSRP deployments that use client timestamps (in GMT) as the ordering field, when we use p2p sync we use this method, important because there is sync (and potential conflict resolution) occurring without access to a server timestamp. In these situations conflicts are still exceedingly rare, as @kaapstorm pointed out the rareness is due to workflows designed to avoid them. In the p2p case we still maintain a history of all versions.

I think we also have OpenSRP deployments that use monotonically increasing version numbers as the ordering field. Whenever an edit or sync occurs the version number is incremented and there's additional business logic (eg where is it coming from or use this secondary field) to break ties.

For now, one of these approaches would work fine for us, but as we see demand for editing in multiple places (like via a web interface in addition to on a smartphone), we'll need to think more about this. On the implementer side, keeping track of a merge conflicts metric seems like a good way to monitor this issue's priority.

cc @rkodev @dubdabasoduba

**Comment by fredhersch** [comment]
@pld When you say, ..'On the implementer side, keeping track of a merge conflicts metric seems like a good way to monitor this issue's priority' .. do you mean having access to an method in the SDK to return information about data conflicts?

**Comment by pld** [comment]
I think this is out of scope for the SDK, I was thinking along the lines of what data should I bring to the community to make the argument the SDK needs more robust handling of merge conflicts?

telling a story like

> last month we had no conflicts, this month we have a different program management structure and 5% of patient syncs result in conflicts, 2% need manual resolution which takes about 30 minutes a patient, we sync 1000 patients so that's 20 patients or 10 hours of conflict resolution, we'd like to improve the handling

seems like an informative data point

**Comment by fredhersch** [comment]
@pld currently the SDK doesn't provide any information about conflicts .. it just handles them. Would you be expecting a log or something simple like that?

**Comment by pld** [comment]
I think this is all out of scope for the SDK

**Comment by fredhersch** [comment]
Thanks. Based on the discussion, the approach that the FHIR SDK takes is reasonable and should support the common use cases. Noted that  handling conflicts is more of an operational issue. Might be worth us adding something here in terms of 'best practices' to avoid conflicts etc ... or shared lessons from the field.

I'm going to close this issue for now.

**Comment by jingtang10** [comment]
@aditya-07 fyi
