### ISSUE TITLE
Update room version to 2.3.0

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#473]
**Describe the Issue**
https://developer.android.com/jetpack/androidx/releases/room#version_230_3

**Would you like to work on the issue?**
:)

**Comment by aditya-07** [comment]
Yes Sure :)

>

**Comment by yigit** [comment]
I was seeking the code to find what i was referring to but just found another issue, these Transaction annotations are no op:
https://github.com/google/android-fhir/blob/1992c7a03e13f71a88bff72177901bc048237729/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt#L64

Because that is not a class Room parses. Transaction annotation only works on Room DAO's so this code needs to use a real transaction (`db.withTransaction {}` )

The main reason i asked for an update was because I thought we had some TypeConverteer's that needs other values injected but seems like we don't have that case. Regardless, it is still good to update.
