### ISSUE TITLE
Bug/Feat : improving string search or indexing for Human Name and Address 

### ISSUE THREAD

**Issue by epicadk** [google/android-fhir#479]
**Is your feature request related to a problem? Please describe.**

The current way to index Human names and Addresses is to concatenate them using a separator.
https://github.com/google/android-fhir/blob/4a2c5d593b2806cb5fa89140d51795d17700e56d/engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt#L171-L197 

The issue arises when we look at the search implementation. According to the standard's definition for the [Patient.name search param](https://www.hl7.org/fhir/patient.html#search) 

> A server defined search that may match any of the string fields in the HumanName, including family, give, prefix, suffix, suffix, and/or text

However the current implementation only matches the concatenated string as generated in the function linked above. 
For example the search query `Patient.name= Jo` would not match in this case and neither would `Patient.name:exact=John` (using the exact modifier). However according to standard (I have also tested this on HAPI) both these queries should return a match with the name given below.
```
"name": [ {

        "use": "official",
        "family": " Doe",
        "given": [ "John" ],
         "prefix": [ "Mr" ]"

      } ]
```

**Describe the solution you'd like**

To fix this changes need to made either to the search api or the way we index Human names and addresses. I would prefer making changes to the indexing api  and indexing each part of the name separately . So in the above example `John` and `Doe` 
would be to different entries in the `StringIndexEntity` table.
 This would be easier to implement and would provide consistent with those of the HAPI fhir server. The drawback is we would need to 

**Describe alternatives you've considered**

Make a changes to the search api, this method would involve using wild card operators in the sql search ( Using the contains query if the param is a name or address). This would cause slower queries. Also consider the case where the search query is `ohn Doe`
This would still match with the name given above however this should not be the case according to the standard.

**Would you like to work on the issue?**

Yes

**Comment by epicadk** [comment]
Not sure whether to classify this as a bug or a feature : /. I'm leaning more towards bug. 
I am happy to take this up once/if we've decided this needs to be address and have reached a consensus on whether the indexing code needs to change or the search code.

**Comment by epicadk** [comment]
@jingtang10 can you share your thoughts here?

**Comment by jingtang10** [comment]
Thanks so much for raising this.

I think, with the implementation of the `:contains`, this issue is somewhat less of a problem. I think I would be content with the fact that anyone can search for "John" with `:contains` using `Patient.name`, and if they want to have the exact match of first name `John` they can always use `John` with `Patient.given` search param.

It seems to me this is only really a problem if the user of the library knows exactly what name they want to match but don't actually know if it's first or last name, OR if they're search for precise prefix/suffix which I think is a very rare use case?

@fredhersch to prioritise. My initial sense is that this is probably medium to low priority.

A final thought: I don't think we are in a position to implement the FHIR specifications to the letter -- for a start it's not written for a programatic API, it's written for RESTful APIs. So we take it as guidance and support as many usecases as possible but it doesn't mean we need to implement everything.

**Comment by epicadk** [comment]
@jingtang10 Thanks. I believe what you said here also applies to #488 and it's corresponding issue.

**Comment by Tarun-Bhardwaj** [comment]
@epicadk , is there anything left to address beyond what #488 is fixing?

**Comment by epicadk** [comment]
> @epicadk , is there anything left to address beyond what #488 is fixing?

Nope, this can be closed
