### ISSUE TITLE
Provide a `StateFlow` for sync status

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#554]
**Is your feature request related to a problem? Please describe.**
We should provide developers access to the status of the sync jobs in order to update the UI.

**Describe the solution you'd like**
We could use a `StateFlow` to wrap the state of the work manager

https://developer.android.com/kotlin/flow/stateflow-and-sharedflow

**Describe alternatives you've considered**
Use `LiveData`: https://developer.android.com/codelabs/android-workmanager#7

@yigit made the recommendation that `StateFlow` is the new API and we should use it. This article talks about hwo to replace `LiveData` with `StateFlow`: https://betterprogramming.pub/android-data-binding-with-mvvm-using-stateflow-and-viewmodel-bce04d0b9bc4

**Additional context**
NA

**Would you like to work on the issue?**
NA

**Comment by Manikant25** [comment]
@jingtang10 Can I take this issue?

**Comment by jingtang10** [comment]
> @jingtang10 Can I take this issue?

Really sorry but Maimoona was already working on this. Thanks for your enthusiasm please keep an eye on the repo and we can assign you something else.

**Comment by Manikant25** [comment]
No problem

**Comment by Tarun-Bhardwaj** [comment]
@maimoonak , is there an ETA by when this issue can be closed? It is blocking #605 which is a high priority for Q3 v0 release.

**Comment by Tarun-Bhardwaj** [comment]
> @maimoonak , is there an ETA by when this issue can be closed? It is blocking #605 which is a high priority for Q3 v0 release.

@maimoonak , any update on the ETA by when this issue can get closed?

**Comment by maimoonak** [comment]
There are multiple options to run polling with flows. 
- channelFlow : allows elements to be produced running in a different context or concurrently (would be helpful when we need to run the sync for resources concurrently and wait until whole sync completes itself, would be needed for sync-workers)
- stateFlow, sharedFlow, tickerFlow (obsolete): For poller we do not need any custom handling or complex flow, so we just implement simple channelFlow. 

interface SyncJob -> to allow multiple or different polling strategies
class SyncJobImpl -> first basic polling implementation with given delay 

https://github.com/google/android-fhir/commit/19b2e2647031af739bb37dd42bf49328fa4c83c5 very basic polling with test

**Comment by maimoonak** [comment]
@Tarun-Bhardwaj I tried my best to finish this by this week. However, it looks like in initial discussions we had missed the power that WorkManager gives. I have  pushed the code with tests on branch 554_flowapi for onetime sync with flow API, and  now trying to see if we can use WorkManger with flow. The WorkManger creates the instances itself and provides a very limited access to running service data later, but we can not avoid it because we want service run even if app is closed, which is provided by WorkManager only. 
@jingtang10 need your help with Periodic Sync with WManger and further discussions on this

**Comment by maimoonak** [comment]
@jingtang10 So based on few things missing into our last discussion I have added a complete workflow which implements one-time-sync and polling as well. Both use flow however, since workmanager does not work on flows, I have a doubt on the approach. I also have made the code a little verbose by adding questions and extra comments which would be deleted before making a formal PR. However, I have much more clarity and answers to queries raised in previous discussion. 
https://github.com/google/android-fhir/pull/648/files this PR reflects the work. Kindly review and then we can discuss it further
