### ISSUE TITLE
Add click to sync option into demo app

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#605]
User story: As a logged in user I can choose to sync the mobile client with a FHIR server and visually see the status changes

Steps:
- User is logged in
- Clicks on the settings which opens a drawer menu
- From the drawer menu, user can see sync option and last sync'd time/date
- User clicks the sync option which starts the sync process. The status changes visually by showing a spinner (or other) and continues in the background

End state:
- On completion, shows a status change (complete) and summary of # records syncd
- On error, will attempt to retry until it either completes or fails. Status should reflect this

**Comment by aditya-07** [comment]
@fredhersch @jingtang10 Since there is no way as of now to know the state of Sync from reference app, I am adding just a sync button on the Top bar. Clicking the button starts a Sync job and shows a Snackbar with sync message at the bottom of the screen and disappears after sometime . We can implement the Drawer with the UI explained in the ticket once we have an API to know the sync state.
