### ISSUE TITLE
Crash on configuration change with a large questionnaire

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#672]
**Describe the bug**
App crashes with configuration change while using a large questionnaire

**Component**
datacapturegallery

**To Reproduce**

1. Use the questionnaire attached in this issue
2. Minimize the application after rendering the quesitonnaire

**Expected behavior**
App should not crash and the current state should be available

**Smartphone (please complete the following information):**
- OnePlus 7t Pro

[questionnaireLarge.txt](https://github.com/google/android-fhir/files/6870052/questionnaireLarge.txt)

**Comment by joiskash** [comment]
Temporarily fixed by putting...

```
override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.clear()
    }
 ```
in the parent activity. Seems like the outState Bundle is too big to save.

**Comment by joiskash** [comment]
ETA 19th August 2021

**Comment by stevenckngaa** [comment]
The issue indeed is caused by storing Questionnaire Json in the bundle [here](https://github.com/google/android-fhir/blob/6ea9f0bb91fa4574c45de4601270cae864b7e0b2/datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt#L72). Rather than storing the questionnaire json, we could store the json file path and load the json from the disk if not previously cached in the memory. [Here](https://github.com/google/android-fhir/blob/1e9fe1c4219d38ae547bb82d8fca6d0c256a7ce6/datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt#L26) is an existing example.

@jingtang10 WDYT?

**Comment by jingtang10** [comment]
What I don't quite understand about this issue is that, if we're hitting the size limit of bundle (https://developer.android.com/guide/topics/resources/runtime-changes) why doesn't it crash when we first use the bundle to pass data to `com.google.android.fhir.datacapture.QuestionnaireFragment` but only crashes upon configuration change? @yigit @kevinmost ideas?

Discussed with @stevenckngaa who sent out a fix #745. His fix allows the developers to pass to `com.google.android.fhir.datacapture.QuestionnaireFragment` an URI rather than the actual questionnaire content. I'm a bit in two minds about this... This solves the problem nicely but I don't really want the library to take on too many responsibilities :)

Another potential fix is to just share the view model with the developer. `com.google.android.fhir.datacapture.QuestionnaireViewModel` is `internal`. I feel we should just open it up so the gallery app can just directly set data on the view model.

**Comment by jingtang10** [comment]
@joiskash can you please try if this works for you? #746

**Comment by yigit** [comment]
we actually discussed this in the initial PR.

It is quite possible that we don't hit it at first because we are just close to the limit and then when UI adds its own data, it pushes us over the edge.

We need to write a mechanism to save these questionaires to disk and also cleanup.

I don't think the URI solves the problem, it mostly just moves it around and adds complexity. I think we would be much better off w/ a file system based methodology that also does cleanup.

**Comment by stevenckngaa** [comment]
Jing and I did discuss the save questionnaires to disk before the prototype. We both think that's a good idea.

In #745, I did save the questionnaire to external cache directory. The reason I opt for URI is that we can later refactor the code to use `InputStream`. By using [IParser#parseResource](https://hapifhir.io/hapi-fhir/apidocs/hapi-fhir-base/ca/uhn/fhir/parser/IParser.html#parseResource(java.io.InputStream)), we can create questionnaire without caching large JSON in memory.

**Comment by jingtang10** [comment]
@yigit in #746 I'm making the view model visible to the library client (no longer internal). It is then a shared view model and the client can interact with it rather than passing a data bundle to the fragment.

we followed the documentations here https://developer.android.com/topic/libraries/architecture/viewmodel#sharing

this would alter the way the client uses the library but i have confirmed it does fix the issue on my device.

**Comment by stevenckngaa** [comment]
While the binder limit is avoided in #746, the questionnaire JSON text is still being cached in the memory of the `ViewModel` alongside with the `Questionnaire` object. Is there any concern of extensive memory usage while loading a large questionnaire in particular on low end devices?

**Comment by joiskash** [comment]
> 
> 
> While the binder limit is avoided in #746, the questionnaire JSON text is still being cached in the memory of the `ViewModel` alongside with the `Questionnaire` object. Is there any concern of extensive memory usage while loading a large questionnaire in particular on low end devices?

Yes, we have seen a lot of crashes related to OOM on low end devices. So it will be best for us to not have copy of the same data in two different formats.

**Comment by anita-vadverao** [comment]
Tested on Different devices by adding large questionnaire mention in above issue. App crash not observed.
