### ISSUE TITLE
Canonical Types are not being handled yet in fhir sdk

### ISSUE THREAD

**Issue by MuhammadSalman-7214** [google/android-fhir#694]
**Describe the bug**
Any resource containing canonical references is not storing in the database. Reason is Class ResourceIndexer line 249 where it tries to cast canonical type into reference entity, which is throwing class cast exception. So far resources checked for this problem are Activity Definition, Observation, Library and Plan Definition.
Standard url for hl7 is https://www.hl7.org/fhir/plandefinition-example.json.html, (See Library Property)

**Component**
Syncing

**To Reproduce**
In attached screenshot Library is valid url as per the documentation, but it will fail to store this resource in the database during syncing when it will try to convert this canonical url into reference entity type, similarly it can be seen for any such url.

**Expected behavior**
Canonical type should remain as canonical type instead of casting as reference entity

**Screenshots**
Screenshot Added
![Screenshot from 2021-07-29 15-00-38](https://user-images.githubusercontent.com/64642723/128839846-a309754b-51e8-423d-b420-f33e5ad2d8f8.png)

**Smartphone (please complete the following information):**

**Additional context**

**Would you like to work on the issue?**
No
![Screenshot from 2021-07-29 14-43-34](https://user-images.githubusercontent.com/64642723/128839478-98bd28fe-cab3-4d36-9191-1706d49b3d2b.png)

**Comment by jingtang10** [comment]
thanks for creating the issue!

**Comment by MuhammadSalman-7214** [comment]
your welcome @jingtang10

**Comment by maimoonak** [comment]
The FHIR sdk treats Canonical and Reference in same way and the StringParam could be Reference or Canonical type. We need to resolve the type explicitly later. The type is resolved and returned by org.hl7.fhir.r4.utils.FhirPathEngine

![Screenshot from 2021-08-24 14-52-18](https://user-images.githubusercontent.com/4829880/130596681-96d56f0c-7e49-4614-997d-301822a2c0c5.png)

**Comment by maimoonak** [comment]
For Library the issue is on depends-on ([relatedArtifact.resource](https://www.hl7.org/fhir/library-definitions.html#Library.relatedArtifact)) property which is type [canonical](https://www.hl7.org/fhir/metadatatypes-definitions.html#RelatedArtifact.resource) but mapped as reference in Library class. 

```
@SearchParamDefinition(name="depends-on", path="Library.relatedArtifact.where(type='depends-on').resource", 
description="What resource is being referenced", type="reference" )
  public static final String SP_DEPENDS_ON = "depends-on";
  public static final ca.uhn.fhir.rest.gclient.ReferenceClientParam DEPENDS_ON = 
new ca.uhn.fhir.rest.gclient.ReferenceClientParam(SP_DEPENDS_ON);
```

[Canonical Types](https://www.hl7.org/fhir/references.html#canonical) can be a reference to other Resource OR anything else, however, I am still trying to understand difference between Canonical and Reference where both can have have reference to Relative/Absolute/Contained path/url

Changing code to 

```
    return value.let {
      when (value) {
        is Reference -> value.reference
        is CanonicalType -> value.asStringValue()
        else -> throw UnsupportedOperationException("Value $value is not readable by SDK")
      }
    }?.let { ReferenceIndex(searchParam.name, searchParam.path, it) }
```

resolved the issue for Library however, the problem for Observation looks different (under progress)
