### ISSUE TITLE
Create new resources on the server using POST

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#760]
We need to support [create](https://hl7.org/fhir/http.html#create) using POST in the sync API.

<s>
**Describe the bug**
Locally created Resources are assigned ID at creation/before saving to the local db. Once this Resource is up-synced, the server assigns a new ID to the resource and disregards the assigned ID  (in case of HTTP-POST). The created object is returned  in the POST response. 
Since the lD for local & remote copy are different now, need to update all the local id references with the remote id.

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.
</s>

**Comment by jingtang10** [comment]
lowering the priority since we do not use POST any more. we are explicitly supporting PUT for creating resources (for now). it is possible that we will need to add support for POST in the future so keeping this issue open.

**Comment by jingtang10** [comment]
We have been working on a number of PRs to redesign the upload process in order to support this feature:

- https://github.com/google/android-fhir/pull/2156
- https://github.com/google/android-fhir/pull/2166
- https://github.com/google/android-fhir/pull/2137
- https://github.com/google/android-fhir/pull/2121
- https://github.com/google/android-fhir/pull/2147
- https://github.com/google/android-fhir/pull/2109
- https://github.com/google/android-fhir/pull/2168

There will be another PR introducing upload strategies and then the PR to update the IDs after POST.

@omarismail94 @anchita-g
