### ISSUE TITLE
Support enableWhenExpression

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#819]
**Is your feature request related to a problem? Please describe.**
See enableWhenExpression mentioned in http://build.fhir.org/ig/HL7/sdc/expressions.html

**Describe the solution you'd like**
Probably use fhir path engine to evaluate the expression to assist enablement evaluation.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you like to work on the issue?**
NA

**Comment by fredhersch** [comment]
@jingtang10 updated the issue to reference the more recent specification page - http://build.fhir.org/ig/HL7/sdc/expressions.html

**Comment by delcroip** [comment]
Hello,
as discuss in the dev call, i'd like to say that this feature is a must have for the EmCare project because the business skip logic cannot rely on "enableWhen" because it allows only OR or AND not a mix of OR and AND unlike the "enableWhenExpression" that is much more flexible

**Comment by fredhersch** [comment]
Thanks @delcroip 

@kunjan8794 Is this something that the Argusoft team could potentially work on?

cc: @jingtang10

**Comment by Tarun-Bhardwaj** [comment]
@prajapati-chirag , is there any progress that you have made on this?
CC: @kunjan8794

**Comment by Tarun-Bhardwaj** [comment]
@f-odhiambo , can someone from your team pick this up as part of Sprint 2?
CC: @fredhersch

**Comment by kunjan8794** [comment]
@fredhersch @jingtang10 the link below has the measurements questionnanire that has some FHIRPath enableWhen expressions.

https://github.com/WorldHealthOrganization/smart-emcare/blob/pyfhirsdc/input/resources/questionnaire/questionnaire-EmCare.B6.Measurements.json

**Comment by RaaziaTarique** [comment]
In order to provide `enableWhenExpression` support in SDK I am going to extend `EnablementEvaluator's evaluate` method functionality by adding support for enableWhenExpression using `FhirPathEngine`
I tried to implement the example present in this link http://build.fhir.org/ig/HL7/sdc/expressions.html. Such as, 
`"expression": "%resource.repeat(item).where(linkId='4.2.1').answer.value.code ='female' and today().toString().substring(0, 4).toInteger() - %resource.repeat(item).where(linkId='4.2.5').answer.value.toString().substring(0, 4).toInteger() >= 40"` 
FhirPathEngine is able to evaluate this expression but it is not able to evaluate expression similar to this `%EmCare.B6.DE02 = true"` one. 
@delcroip can you verify if this expression is correct? CC: @ekigamba @fredhersch @Tarun-Bhardwaj @jingtang10

**Comment by delcroip** [comment]
@RaaziaTarique  to be honest we are waiting for the support on fhirpath to work on the condition


Fhirpath says that we can use the linkid like %linkid but we might change it to %'linkid', 
http://build.fhir.org/ig/HL7/sdc/expressions.html#fhirpath-supplements see %context part

therefore the  %EmCare.B6.DE02 = true might need to become  %'EmCare.B6.DE02' = true

**Comment by ekigamba** [comment]
@RaaziaTarique Based on what @delcroip has linked, it seems that we also need to support the following FHIR Path supplements:

- `%resource`
- `%context`
- Variables defined in the current item or parent item eg. if a variable was defined as `score` then this should be accessible later in the same item or descendant/child item as `%score
- `%questionnaire`
- `%qitem`

@delcroip I don't seem to find the spec that defines you example. Could you provide another example. We are also having trouble running it successfully.

@RaaziaTarique Let's see if we can support this and have tests for this since it's deifned under the spec and should be supported. However, I think some of the supplements do not make sense for the `enableWhen` expression eg. the `%qItem`. This does not have a use since you cannot have an `enableWhen` expression that depends on the current questionnaire response item's value

**Comment by ekigamba** [comment]
It seems that our current FHIR Path version does not natively support %questionnaire` and `%qitem`. The two are described as extensions and have been adopted as `local` FHIRPath extensions..

As per http://build.fhir.org/ig/HL7/sdc/expressions.html#fhirpath-supplements
> These extensions have been adopted as 'local' FHIRPath extensions for implementers of this implementation guide. Systems that accept FHIRPath, CQL or FHIRQuery expressions SHOULD support all of these extensions in their FHIRPath implementations:

**Comment by RaaziaTarique** [comment]
- `FhirPathEngine` currently supports `%resource` and `%context` and they both work similarly, as `%context`  is pointing to the provided  resource however it should point to the current traversed Item which can be the root of the `QuestionnaireResponse` or `QuestionnaireItem` .  If more supports needed for `%context`  then another issue can be created for it.
- Right now sdk is not supporting variable expression and we have an active issue related to it https://github.com/google/android-fhir/issues/1059 
CC: @ekigamba @f-odhiambo @delcroip @Tarun-Bhardwaj @jingtang10

**Comment by delcroip** [comment]
Thank @ekigamba, after reading it again it seems that i misunderstood, %context works only for the current linkid, as you said, I didn't found what can define my example. (it would have make the enableWhenExpression much clearer)

I will update to something similar to the structure proposed 
```
%resource.repeat(item).where(linkId='4.2.1').answer.value.code ='female'
```

br
