### ISSUE TITLE
Read only view in questions/forms too light

### ISSUE THREAD

**Issue by mberg** [google/android-fhir#917]
**Describe the bug**

The read only view on questions are a bit too gray (from my perspective) making them hard to read. I expect this to be an issue with quite a few of our users who may have poor eyesight.  I'm not sure if this is the Android default but I'd recommend we go with a much darker version of gray if possible.  

**Component**

SDC library

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by mberg** [comment]
![Screenshot_1636632533](https://user-images.githubusercontent.com/57921/141295611-4ac7f0c7-0304-424f-8c5e-6d1770646b76.png)

**Comment by jingtang10** [comment]
@santosh-pingle

**Comment by jingtang10** [comment]
@shelaghm

**Comment by jingtang10** [comment]
i agree with you here @mberg it's too light... we're just doing the default thing here... but may need to change that... thanks so much for the feedback!

does material have support for this type of stuff @shelaghm?

**Comment by shelaghm** [comment]
@jingtang10 @mberg @santosh-pingle 
Yes, the contrast does seem very low, which makes this text not accessible/legible. Looking at the Material guidelines, they use 38% opacity for disabled text. @jingtang10 can you check what is implemented? From looking at colors in figma it looks like our implementation is a bit lighter than what's specified. 

I recommend we use 38% Opacity of #000000 or 9E9E9E for disabled/read only text and containers.

However, I think there are two other UX challenges here.
1. It is not necessarily obvious to the user that this text is disabled/read only, just because we have applied the disabled text color style. I propose we add additional language in the 'helper text line' to the content pieces that are disabled to indicate they are read only/cannot be edited. (see screenshot) 
2. It's uncommon to use the disabled text styling for such large blocks of text, and typically disabled text needs to be shown in comparison with enabled text for it to be obvious that it is disabled. I propose we increase the default to what's specified above and optionally add an icon to make it more clear it is view only. It might be a bit tricky to select an icon that is intuitive, that's where the 'helper text line' is crucial. 

<img width="920" alt="Screen Shot 2021-11-15 at 1 49 42 PM" src="https://user-images.githubusercontent.com/86378921/141793614-86c85810-9ca7-4da9-89d6-e0fff320ec26.png">

**Comment by Tarun-Bhardwaj** [comment]
@santosh-pingle , please upload a screen shot once the changes are complete.

**Comment by mberg** [comment]
Thanks @shelaghm I think that looks a lot better!  I think having the eye in every field may be a bit more then what we want to go for. 

For a bit of context, we'll probably be using this as an interim hack to view filled out forms for now.  I realize there are better UX approaches for that but that's an initial way I think people will be using it.

@jingtang10 do we have thoughts on a version of this can render a questionnaire response out in an array or some format we can visualize including support for things like skip logic?

**Comment by jingtang10** [comment]
> @jingtang10 do we have thoughts on a version of this can render a questionnaire response out in an array or some format we can visualize including support for things like skip logic?

hey matt - not totally sure of the requirement here. do you mean like a summary table after the questionnaire is filled out?

**Comment by santosh-pingle** [comment]
@jingtang10 

readOnly view state (text and the outline of the text box when state is disabled/enabled) are implemented for edit text view.
Created PR https://github.com/google/android-fhir/pull/939 for proposed solution, could you please check once?

Also, there are other views such as `autoComplete view, checkbox group view, radio group view, datetime picker view, time picker view... and many more`, do we need to apply readonly changes to all these views?

Please confirm once.

Before implementation 
_Edittext view with Mark input_
<img width="430" alt="Screen Shot 2021-11-24 at 3 21 36 PM" src="https://user-images.githubusercontent.com/86107848/143218166-22792952-0357-41fe-8f7a-4c231c08ac2c.png">

After implementation
_Edittext view with Mark input_
<img width="433" alt="Screen Shot 2021-11-24 at 3 24 29 PM" src="https://user-images.githubusercontent.com/86107848/143218198-ba122081-ca2d-4c1f-b555-83d19b51345b.png">
