### ISSUE TITLE
Support calculatedExpression

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#971]
**Is your feature request related to a problem? Please describe.**
See #803

See example of calculatedExpression and variable: http://build.fhir.org/ig/HL7/sdc/examples.html#using-calculatedexpression-and-variable

@maimoonak provided this example where we want to take age OR birthdate as input and calculate the other from one which was input: https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_calculatedexpression.json

**Describe the solution you'd like**
Probably use FHIRPath

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you like to work on the issue?**
NA

**Comment by jingtang10** [comment]
@maimoonak @f-odhiambo can you please comment on the priority of this issue and if you have any bandwidth to take this on? thanks!

**Comment by maimoonak** [comment]
Rightnow this issue is not a blocker for us. However, many of the forms we have seen in previous apps included the calculated expressions to make forms concise and self dependent and also accommodate simple decisions for Health workers. A very common example is deriving risk factor for patient OR calculate next followup date. I would rate this 4/5 on priority. 
This issue seems complex and might need a lot of input on design hence before committing on this we would need to have a discussion on the approach and design.

**Comment by fredhersch** [comment]
@maimoonak is 4/5 high or low priority? Thanks for the comments!

**Comment by delcroip** [comment]
Hello,
as discuss in the dev call, i'd like to say that this feature is a must have for the EmCare project because the business wants to have calculation result display on the questionnaire

**Comment by fredhersch** [comment]
Thanks @delcroip 

@kunjan8794 Is this something that the Argusoft team could potentially work on? 

cc: @jingtang10

**Comment by Tarun-Bhardwaj** [comment]
@kunjan8794 , did you get a chance to work on this?

**Comment by Tarun-Bhardwaj** [comment]
@f-odhiambo , can someone from your team pick this up as part of Sprint 2?
CC: @fredhersch

**Comment by fredhersch** [comment]
@f-odhiambo I noticed @maimoonak's comment about design. Let's make sure we spend some time on this before we dive into the implementation.

**Comment by f-odhiambo** [comment]
@Tarun-Bhardwaj Kindly assign this ticket to @maimoonak

**Comment by maimoonak** [comment]
The [draft PR](https://github.com/google/android-fhir/pull/1380) for current issue has basic implementation. 
- The app runs calculated-expression for fields having extension
- It update the fields and returns correct value in questionnaireResponse
- App has an implementation in 'catalog' as well

Issues
- Still figuring out why app is not updating the value on UI (despite that value is updated and exists in  questionnaireResponse and maps of linkId-Item)
- The cyclic dependency between two variables can lead to unexpected results and since it is expression we do not have any way determining what variables are dependent on other. For. e.g. in example where birthdate updates age and age updates birthdate, the evaluation of expression can lead to setting both fields null or update both values which completely depends on sequence app loops over link-id map. It means that user should be aware that they should avoid cyclic dependencies over such extensions. If two fields or more  are responsible for maintaining a value a thrid field should be used keep most recent value.
- Using variables would be possible as soon as https://github.com/google/android-fhir/pull/1328 is merged and the data is passed into the evaluator running calculated-expression

**Comment by maimoonak** [comment]
PR for issue is ready for review
- working feature
- cyclic dependency detection on load
- on load and on update item value detection and reflection on UI.

@f-odhiambo @fredhersch
