### ISSUE TITLE
Data input widget always open if it's the first input of the page

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#973]
This is a good fix! Another issue I have noticed is with the Date and time widget. Please have a look at the video that I have attached. I think you can add some similar check which will prevent this from happening. It happens with the drop down too. 

https://user-images.githubusercontent.com/48797364/145559102-660a992a-36d7-49f2-9ced-de6b570f59ad.mp4

.

_Originally posted by @joiskash in https://github.com/google/android-fhir/pull/957#pullrequestreview-828732707_

**Comment by jingtang10** [comment]
@joiskash: There is no crash, but the date widget pops up every time the cursor is on the first widget and the page is changed. Its a bug. The date widget should not pop-up unless clicked on.

**Comment by jingtang10** [comment]
with the changes being done in the catalog app - to reproduce this we need to change the navigation graph when building the catalog app

**Comment by PallaviGanorkar** [comment]
@jingtang10 , As mentioned above, after changing navigation graph in the catalog app, I could not find Date and time widget for ANC ID field. Instead of Date and time widget there is TextView and only onclick action it opens Keyboard. Screenshot is attached for more details.

![Screenshot_1642774556](https://user-images.githubusercontent.com/13957417/150542954-8d1460e9-a19d-480c-a6a2-21cb1d10c464.png)

**Comment by PallaviGanorkar** [comment]
![Screenshot_1642775078](https://user-images.githubusercontent.com/13957417/150543343-9f2e4956-e030-4027-96cb-baa6828f9348.png)

**Comment by Anshul-9923** [comment]
@jingtang10 If this issue is not resolved yet, can you assign me this issue?

**Comment by samiali12** [comment]
Please assign me this issue if this is not resolved.

**Comment by jingtang10** [comment]
ah sorry! @PallaviGanorkar 

in this case just change the question type in the json file from text to date locally: https://github.com/google/android-fhir/blob/fa51f691cf4c3fecf86f8b7250386112a8e34cc9/catalog/src/main/assets/patient-registration-paginated.json#L30

**Comment by jingtang10** [comment]
also related to #1089 - i wonder if it will fix this.

**Comment by santosh-pingle** [comment]
@PallaviGanorkar 
Hide the bottom navigation view as well to get the Previous and Next buttons at the bottom to navigate forth and back if you want to use old sdc reference app to reproduce this issue.
`activity_main.xml` 
```
 <com.google.android.material.bottomnavigation.BottomNavigationView
        android:visibility="gone"
        android:id="@+id/bottom_navigation_view"
        ....
```

https://user-images.githubusercontent.com/86107848/154636838-01a5c4e0-45b0-4b32-83f9-4f6a612417e9.mov


Or catalog app can also be used to reproduce this issue
layout -> paginated

https://user-images.githubusercontent.com/86107848/154637397-ee6c7480-5fbe-4c31-8244-0332a09122e8.mov

**Comment by PallaviGanorkar** [comment]
Based on the comments in PR https://github.com/google/android-fhir/pull/1089 and as discussed with @jingtang10   , If date entry format received from questionnaire JSON, then date input widget must show it as helper text otherwise date entry format must be read from device base on locale and show as helper text.

**Comment by PallaviGanorkar** [comment]
This functionality implemented in https://github.com/google/android-fhir/pull/1275
