### ISSUE TITLE
Sdc gallery app, show gear menu icon in actionbar. 

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#996]
**Is your feature request related to a problem? Please describe.**
1. Show gear menu icon in action bar for all questionnaire screen when user navigate from landing page to questionnaire.
2. Hide gear icon from action bar, when user navigate back to the landing page.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by shelaghm** [comment]
@santosh-pingle do you have a separate issue for what happens when a user taps the gear icon?

1. First time a user taps on a component, the user sees a "hint" to press the gear icon. See screenshot below. Only show this once.
![Screen Shot 2022-01-04 at 16 11 04](https://user-images.githubusercontent.com/86378921/148140829-34430c8f-f5d2-4b3f-90ea-aa7356cf6e64.png)

**Comment by varunkuar8789** [comment]
productivity with telecommuting tools

**Comment by santosh-pingle** [comment]
Bottom sheet and gear icon are not used in catalog app, as per latest UX guideline.
